#!/usr/bin/env python3
"""Writes assets/scenes/tests/physics/ragdoll_test/scene.yaml -- the ragdoll bench.

Three mannequin_ragdoll instances start limp at the top of a flight of stairs with a shove down
it; a kinematic ram sweeps the landing at the bottom, pushing whatever lies there; a fourth
mannequin is a CharacterController player whose Ragdoll reacts to R (go limp / recover).

Run:  python3 tools/gen_ragdoll_test_scene.py
"""

import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "scenes", "tests", "physics",
                   "ragdoll_test", "scene.yaml")

STEPS = 8           # stairs: 8 steps of 0.3 m rise, 0.55 m run, descending toward +Y
RISE, RUN = 0.3, 0.55
TOP_Z = STEPS * RISE
STAIR_Y0 = -4.0     # the top landing ends (and the first step starts) here
WIDTH = 6.0


def num(x):
    return f"{x:.4g}"


def box(name, pos, size, material, comment=None, extra=()):
    out = []
    if comment:
        out.append(f"    # {comment}")
    out += [
        f"    - name: {name}",
        "      components:",
        "        - type: Transform",
        f"          position: {{ x: {num(pos[0])}, y: {num(pos[1])}, z: {num(pos[2])} }}",
        "          rotation: { x: 0, y: 0, z: 0 }",
        f"          scale: {{ x: {num(size[0])}, y: {num(size[1])}, z: {num(size[2])} }}",
        "        - type: MeshRenderer",
        "          mesh_path: cube",
        f"          material: {material}",
        "        - type: BoxCollider",
        "          size: { x: 1.0, y: 1.0, z: 1.0 }",
    ]
    out += list(extra)
    out.append("      children: []")
    out.append("")
    return out


def mannequin(name, pos, yaw, components, comment=None):
    out = []
    if comment:
        out.append(f"    # {comment}")
    out += [
        f"    - name: {name}",
        "      prefab: objects/mannequin_ragdoll",
        "      components:",
        "        - type: Transform",
        f"          position: {{ x: {num(pos[0])}, y: {num(pos[1])}, z: {num(pos[2])} }}",
        f"          rotation: {{ x: 0, y: 0, z: {num(yaw)} }}",
        "          scale: { x: 1, y: 1, z: 1 }",
    ]
    out += list(components)
    out.append("")
    return out


def main():
    grid = "{ base: materials/prototype_grid, albedo: { r: 0.62, g: 0.62, b: 0.64 } }"
    stair = "{ base: materials/prototype_grid, albedo: { r: 0.55, g: 0.6, b: 0.7 } }"
    ram = "{ albedo: { r: 0.85, g: 0.3, b: 0.15 }, roughness: 0.5 }"
    L = [
        "# ragdoll_test -- the Ragdoll bench: mannequins tumbling down stairs, a ram shoving them across",
        "# the landing, and a player that goes limp and recovers on R.",
        "# GENERATED by tools/gen_ragdoll_test_scene.py; edit that, not this file.",
        "#",
        "# Run: ./build/toyengine ragdoll_test        (or SCENE=ragdoll_test)",
        "# Controls: R toggles the player's ragdoll (limp with a backward shove / blend back into idle),",
        "# WASD walks it, mouse orbits the camera.",
        "#",
        "# Map:",
        f"#   y < {num(STAIR_Y0)}   the top landing ({num(TOP_Z)} m up): three mannequin_ragdoll instances start limp",
        "#              (mode: ragdoll) with a shove toward +Y, down the stairs",
        f"#   y {num(STAIR_Y0)}..{num(STAIR_Y0 + STEPS * RUN)}  {STEPS} steps of {num(RISE)} m, descending toward +Y",
        "#   y ~ 3      the landing: a kinematic ram (red) sweeps along X, pushing the fallen bodies",
        "#   x = 6      the player: CharacterController + CharacterAnimDriver + Ragdoll (input_toggle)",
        "#",
        "# Worth checking: physics debug draw (joints: anchors + cone-twist cones), the bodies settling",
        "# without jitter, R mid-walk (the capsule turns off, recovery stands up where the body lies).",
        "format: blender",
        "scene:",
        "  scene_name: ragdoll_test",
        "  root_objects:",
    ]
    L += box("ground", (0, 0, -0.5), (40, 40, 1), grid, "Ground: a 40 x 40 m slab, top at z = 0.")
    # Top landing, then the steps (each a solid block from the ground to its tread).
    L += box("top_landing", (0, STAIR_Y0 - 2.0, TOP_Z / 2), (WIDTH, 4.0, TOP_Z), stair,
             f"The top landing, {num(TOP_Z)} m up, and {STEPS} steps down toward +Y.")
    for i in range(STEPS):
        h = TOP_Z - (i + 1) * RISE
        if h <= 0:
            continue
        y = STAIR_Y0 + (i + 0.5) * RUN
        L += box(f"step_{i + 1}", (0, y, h / 2), (WIDTH, RUN, h), stair)

    # Three limp mannequins near the top edge, shoved down the stairs.
    for k, x in enumerate((-1.8, 0.0, 1.8)):
        impulse_y = 280 + 40 * k
        L += mannequin(
            f"tumbler_{k + 1}", (x, STAIR_Y0 - 0.6, TOP_Z), 180 if k == 1 else 0,
            ["        - type: Ragdoll",
             "          mode: ragdoll",
             f"          start_impulse: {{ x: {num(30 * (k - 1))}, y: {num(impulse_y)}, z: 140 }}"],
            "Tumblers: limp from the first frame, shoved down the stairs." if k == 0 else None)

    # The ram: a kinematic block sweeping the landing along X.
    land_y = STAIR_Y0 + STEPS * RUN + 1.6
    L += box("ram", (0, land_y, 0.45), (0.8, 3.0, 0.9), ram,
             "The ram: a kinematic block ping-ponging along X across the landing at the stairs' foot.",
             ["        - type: Rigidbody",
              "          is_kinematic: true",
              "          use_gravity: false",
              "        - type: KinematicMover",
              "          mode: pingpong",
              "          axis: { x: 1, y: 0, z: 0 }",
              "          distance: 7.0",
              "          speed: 0.1"])

    # The player: R goes limp (shoved backward) and recovers.
    L += mannequin(
        "player", (7.0, 1.0, 0.0), 0,
        ["        - type: CharacterController",
         "          radius: 0.3",
         "          height: 1.8",
         "          move_speed: 3.0",
         "        - type: CharacterAnimDriver",
         "          crossfade: 0.2",
         "        - type: Ragdoll",
         "          input_toggle: true",
         "          toggle_impulse: { x: 0, y: -60, z: 20 }",
         "          blend_time: 0.6"],
        "The player: R toggles its Ragdoll (linked to the CharacterController).")

    L += [
        "    - name: camera",
        "      components:",
        "        - type: Transform",
        "          position: { x: 7, y: 11, z: 6.5 }",
        "          rotation: { x: 66, y: 0, z: 150 }",
        "          scale: { x: 1, y: 1, z: 1 }",
        "        - type: Camera",
        "          main: true",
        "          projection: Perspective",
        "          fov: 55.0",
        "          near_clip_plane: 0.1",
        "          far_clip_plane: 300.0",
        "        - type: CameraController",
        "          mode: orbit",
        "          target: { x: 0, y: 1, z: 0.8 }",
        "          min_distance: 3.0",
        "          max_distance: 40.0",
        "      children: []",
        "",
        "    - name: sun",
        "      components:",
        "        - type: Transform",
        "          position: { x: 0, y: 0, z: 20 }",
        "          rotation: { x: 0, y: 0, z: 0 }",
        "          scale: { x: 1, y: 1, z: 1 }",
        "        - type: DirectionalLight",
        "          direction: { x: -0.45, y: 0.3, z: -0.84 }",
        "          color: { r: 1.0, g: 0.96, b: 0.9 }",
        "          intensity: 1.0",
        "          cast_shadows: true",
        "      children: []",
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
