#!/usr/bin/env python3
"""Writes the `mannequin`: a humanoid object-hierarchy rig, its capsule part meshes and its clips.

Outputs (all under assets/):
  * objects/characters/mannequin.yaml -- the rig as an OBJECT ASSET (prefab). Place it with
    `prefab: objects/mannequin`; add a CharacterController (+ CharacterAnimDriver) to the
    instance to make it a player (see scenes/tests/gameplay/character_test).
  * objects/characters/mannequin_ragdoll.yaml -- the same rig plus a Ragdoll (capsule/box bones,
    cone-twist hips/shoulders/spine/neck, hinge knees/elbows/ankles; see RAGDOLL below and
    toyengine/scene/ragdoll.h). A separate prefab, so plain mannequins carry no bone bodies.
  * meshes/characters/mannequin_*.yaml -- one capsule mesh per body part (Z-up, centred).
  * animations/mannequin/{idle,walk,run,jump}.yaml -- the clips its Animator plays. walk and run
    carry ROOT MOTION (the pelvis's travel, `root_motion: {object: pelvis, translation: xy}`) and
    `footstep` events (string left / right) as each foot plants.

The rig, Z-up and facing local +Y (its right hand is +X, its left -X), origin at the feet,
about 1.8 m tall -- the default CharacterController capsule (radius 0.3, height 1.8):

  mannequin                      Animator (idle / walk / run / jump)
    pelvis                       z 0.95
      spine                        abdomen
        chest                      torso
          neck
            head                   head + visor (the visor marks the front)
          upper_arm_l / _r         shoulders at x -/+0.21
            lower_arm_l / _r
              hand_l / _r
      thigh_l / _r                 hips at x -/+0.1
        shin_l / _r
          foot_l / _r

Joints are empty objects at their pivots with identity rest rotations; limbs hang along local
-Z, so a positive X rotation swings a limb FORWARD (+Y) and a negative one bends a knee back.
Each visible part is a child `<joint>_shape` of its joint. These names are the rig's contract:
clips address joints by path, and later systems (foot IK, ragdoll bone lists) name them too.

Run:  python3 tools/gen_mannequin.py
"""

import math
import os

ASSETS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets")
MESH_DIR = os.path.join(ASSETS, "meshes", "characters")
OBJECT_PATH = os.path.join(ASSETS, "objects", "characters", "mannequin.yaml")
RAGDOLL_OBJECT_PATH = os.path.join(ASSETS, "objects", "characters", "mannequin_ragdoll.yaml")
ANIM_DIR = os.path.join(ASSETS, "animations", "mannequin")

GENERATED = "GENERATED by tools/gen_mannequin.py; edit that, not this file."


def fmt(v):
    return "[" + ", ".join(f"{x:.6g}" for x in v) + "]"


def num(x):
    return f"{x:.6g}"


# ---------------------------------------------------------------------------------------------
# Capsule meshes
# ---------------------------------------------------------------------------------------------

def capsule_mesh(path, radius, length, sides=16, cap_rings=6):
    """A capsule along Z centred at the origin: `length` between the cap centres (0 = sphere).

    A lathe: rings from the bottom pole to the top pole, a duplicated u = 1 seam column, and
    triangles (not degenerate quads) at the poles.
    """
    half = length * 0.5
    rings = []  # (radius at ring, z, normal_r, normal_z, v)
    for i in range(cap_rings + 1):  # bottom cap, pole -> equator
        a = -math.pi / 2 + (math.pi / 2) * i / cap_rings
        rings.append((radius * math.cos(a), -half + radius * math.sin(a), math.cos(a), math.sin(a)))
    for i in range(cap_rings + 1):  # top cap, equator -> pole
        a = (math.pi / 2) * i / cap_rings
        rings.append((radius * math.cos(a), half + radius * math.sin(a), math.cos(a), math.sin(a)))
    total = (length + 2 * radius) or 1.0
    verts, normals, uvs, faces = [], [], [], []
    row = sides + 1
    for (rr, z, nr, nz) in rings:
        v = (z + half + radius) / total
        for s in range(sides + 1):
            a = 2 * math.pi * s / sides
            c, sn = math.cos(a), math.sin(a)
            verts.append([rr * c, rr * sn, z])
            n = [nr * c, nr * sn, nz]
            ln = math.sqrt(sum(x * x for x in n)) or 1.0
            normals.append([x / ln for x in n])
            uvs.append([s / sides, v])
    last = len(rings) - 1
    for r in range(last):
        for s in range(sides):
            a = r * row + s
            b, c, d = a + 1, a + row + 1, a + row
            if r == 0:
                faces.append([a, c, d])          # bottom pole: ring 0 is a point
            elif r == last - 1:
                faces.append([a, b, c])          # top pole: ring `last` is a point
            else:
                faces.append([a, b, c, d])
    lines = [f"# mannequin part: capsule r {num(radius)}, cap-centre distance {num(length)}, along Z, centred.",
             f"# {GENERATED}",
             "vertices:"]
    lines += [f"  - {fmt([round(x, 5) for x in p])}" for p in verts]
    lines.append("normals:")
    lines += [f"  - {fmt([round(x, 5) for x in n])}" for n in normals]
    lines.append("uvs:")
    lines += [f"  - {fmt([round(x, 5) for x in uv])}" for uv in uvs]
    lines.append("faces:")
    lines += [f"  - {f}" for f in faces]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


# name -> (radius, cap-centre length)
PART_MESHES = {
    "mannequin_pelvis": (0.13, 0.14),
    "mannequin_abdomen": (0.12, 0.08),
    "mannequin_torso": (0.16, 0.14),
    "mannequin_head": (0.11, 0.05),
    "mannequin_neck": (0.05, 0.04),
    "mannequin_upper_arm": (0.055, 0.17),
    "mannequin_lower_arm": (0.047, 0.16),
    "mannequin_hand": (0.045, 0.05),
    "mannequin_thigh": (0.08, 0.27),
    "mannequin_shin": (0.062, 0.29),
    "mannequin_foot": (0.05, 0.13),
}


# ---------------------------------------------------------------------------------------------
# The rig
# ---------------------------------------------------------------------------------------------

BODY = "{albedo: {r: 0.62, g: 0.66, b: 0.72}, roughness: 0.55, metallic: 0.05}"
LIMB = "{albedo: {r: 0.5, g: 0.54, b: 0.6}, roughness: 0.55, metallic: 0.05}"
DARK = "{albedo: {r: 0.2, g: 0.22, b: 0.26}, roughness: 0.6}"
VISOR = "{albedo: {r: 0.95, g: 0.55, b: 0.15}, roughness: 0.35, emissive: {r: 0.4, g: 0.18, b: 0.04}}"


def joint(name, pos, children, shapes=()):
    return {"name": name, "pos": pos, "children": list(shapes) + list(children)}


def shape(name, mesh, pos, material, rot=(0, 0, 0), scale=(1, 1, 1)):
    return {"name": name, "pos": pos, "rot": rot, "scale": scale, "mesh": mesh, "material": material}


def arm(side):
    sx = -1 if side == "l" else 1
    return joint(f"upper_arm_{side}", (sx * 0.21, 0, 0.17), [
        joint(f"lower_arm_{side}", (0, 0, -0.28), [
            joint(f"hand_{side}", (0, 0, -0.25), [], [
                shape(f"hand_{side}_shape", "mannequin_hand", (0, 0, -0.07), DARK)]),
        ], [shape(f"lower_arm_{side}_shape", "mannequin_lower_arm", (0, 0, -0.125), LIMB)]),
    ], [shape(f"upper_arm_{side}_shape", "mannequin_upper_arm", (0, 0, -0.14), LIMB)])


def leg(side):
    sx = -1 if side == "l" else 1
    return joint(f"thigh_{side}", (sx * 0.1, 0, -0.05), [
        joint(f"shin_{side}", (0, 0, -0.43), [
            joint(f"foot_{side}", (0, 0, -0.41), [], [
                shape(f"foot_{side}_shape", "mannequin_foot", (0, 0.06, -0.005), DARK, rot=(90, 0, 0))]),
        ], [shape(f"shin_{side}_shape", "mannequin_shin", (0, 0, -0.205), LIMB)]),
    ], [shape(f"thigh_{side}_shape", "mannequin_thigh", (0, 0, -0.215), LIMB)])


RIG = joint("pelvis", (0, 0, 0.95), [
    joint("spine", (0, 0, 0.1), [
        joint("chest", (0, 0, 0.2), [
            joint("neck", (0, 0, 0.24), [
                joint("head", (0, 0, 0.05), [], [
                    shape("head_shape", "mannequin_head", (0, 0, 0.11), BODY),
                    shape("visor", "cube", (0, 0.085, 0.13), VISOR, scale=(0.16, 0.06, 0.05)),
                ]),
            ], [shape("neck_shape", "mannequin_neck", (0, 0, 0.0), DARK)]),
            arm("l"), arm("r"),
        ], [shape("chest_shape", "mannequin_torso", (0, 0, 0.08), BODY, scale=(1.25, 0.8, 1.0))]),
    ], [shape("abdomen_shape", "mannequin_abdomen", (0, 0, 0.06), BODY, scale=(1.0, 0.8, 1.0))]),
    leg("l"), leg("r"),
], [shape("pelvis_shape", "mannequin_pelvis", (0, 0, 0.0), BODY, rot=(0, 90, 0), scale=(1.0, 0.8, 1.0))])


def vec(label, v):
    return f"{label}: {{x: {num(v[0])}, y: {num(v[1])}, z: {num(v[2])}}}"


def emit_node(node, indent):
    p = " " * indent
    out = [f"{p}- name: {node['name']}", f"{p}  components:", f"{p}    - type: Transform",
           f"{p}      {vec('position', node['pos'])}"]
    if "mesh" in node:
        out.append(f"{p}      {vec('rotation', node['rot'])}")
        out.append(f"{p}      {vec('scale', node['scale'])}")
        out.append(f"{p}    - type: MeshRenderer")
        out.append(f"{p}      mesh_path: {node['mesh']}")
        out.append(f"{p}      material: {node['material']}")
        out.append(f"{p}  children: []")
        return out
    out.append(f"{p}      rotation: {{x: 0, y: 0, z: 0}}")
    out.append(f"{p}  children:" + ("" if node["children"] else " []"))
    for child in node["children"]:
        out += emit_node(child, indent + 4)
    return out


# Ragdoll bones: (path, shape, shape params, mass kg, joint). Shapes sit along each bone toward
# its child (limbs hang along -Z); joints connect to the nearest ancestor bone in this list and
# are measured from the bind pose (identity rest rotations). Positive X swings a limb forward, so
# a knee bends in [-140, 0] and an elbow in [0, 140]. Hands and the neck stay out (they ride
# their parent bone): fewer, heavier bodies keep the chain stiff and calm.
def _vec(v):
    return "{x: %s, y: %s, z: %s}" % tuple(num(c) for c in v)


def _cone(axis, swing, twist, anchor=None):
    j = [("joint", "cone_twist")]
    if anchor:
        j.append(("anchor", _vec(anchor)))
    return j + [("axis", _vec(axis)), ("swing", num(swing)), ("twist_min", num(-twist)), ("twist_max", num(twist))]


def _hinge(lo, hi):
    return [("joint", "hinge"), ("axis", _vec((1, 0, 0))), ("limit_min", num(lo)), ("limit_max", num(hi))]


RAGDOLL = [
    ("pelvis", "capsule", {"radius": 0.12, "height": 0.32, "direction": "x"}, 12.0, None),
    ("pelvis/spine", "capsule", {"radius": 0.11, "height": 0.36, "direction": "x", "center": (0, 0, 0.08)}, 8.0,
     _cone((0, 0, 1), 25, 20)),
    ("pelvis/spine/chest", "capsule", {"radius": 0.13, "height": 0.44, "direction": "x", "center": (0, 0, 0.1)}, 12.0,
     _cone((0, 0, 1), 20, 20)),
    ("pelvis/spine/chest/neck/head", "sphere", {"radius": 0.12, "center": (0, 0, 0.11)}, 5.0,
     _cone((0, 0, 1), 35, 45, anchor=(0, 0, -0.05))),
]
for _s in "lr":
    RAGDOLL += [
        (f"pelvis/spine/chest/upper_arm_{_s}", "capsule", {"radius": 0.055, "height": 0.28, "center": (0, 0, -0.14)}, 2.5,
         _cone((0, 0, -1), 80, 45)),
        (f"pelvis/spine/chest/upper_arm_{_s}/lower_arm_{_s}", "capsule",
         {"radius": 0.04, "height": 0.36, "center": (0, 0, -0.17)}, 2.0, _hinge(0, 140)),
        (f"pelvis/thigh_{_s}", "capsule", {"radius": 0.08, "height": 0.43, "center": (0, 0, -0.215)}, 8.0,
         _cone((0, 0, -1), 60, 30)),
        (f"pelvis/thigh_{_s}/shin_{_s}", "capsule", {"radius": 0.062, "height": 0.41, "center": (0, 0, -0.205)}, 4.0,
         _hinge(-140, 0)),
        (f"pelvis/thigh_{_s}/shin_{_s}/foot_{_s}", "box", {"size": (0.1, 0.24, 0.08), "center": (0, 0.06, -0.015)}, 1.0,
         _hinge(-30, 40)),
    ]


def ragdoll_component():
    out = ["    - type: Ragdoll",
           "      mode: animated",
           "      blend_time: 0.6",
           "      recover_state: idle",
           "      drag: 0.05",
           "      angular_drag: 0.8",
           "      bones:"]
    for path, shape, params, mass, joint in RAGDOLL:
        out.append(f"        - bone: {path}")
        out.append(f"          shape: {shape}")
        for key in ("radius", "height", "direction"):
            if key in params:
                v = params[key]
                out.append(f"          {key}: {v if isinstance(v, str) else num(v)}")
        if "size" in params:
            out.append(f"          size: {_vec(params['size'])}")
        if "center" in params:
            out.append(f"          center: {_vec(params['center'])}")
        out.append(f"          mass: {num(mass)}")
        for key, value in joint or ():
            out.append(f"          {key}: {value}")
    return out


def write_object(path=OBJECT_PATH, extra_components=(), header_note=None):
    lines = [
        "# mannequin: a 1.8 m humanoid object-hierarchy rig (joints are empties, parts are capsule",
        "# meshes), facing +Y, origin at the feet. Clips idle / walk / run / jump. Joint names are a",
        "# contract (clips, foot IK and ragdolls address them) -- see tools/gen_mannequin.py.",
    ]
    if header_note:
        lines.append(f"# {header_note}")
    lines += [
        f"# {GENERATED}",
        "format: toyengine-object",
        "object:",
        f"  name: {os.path.splitext(os.path.basename(path))[0]}",
        "  components:",
        "    - type: Transform",
        "      position: {x: 0, y: 0, z: 0}",
        "    - type: Animator",
        "      auto_play: idle",
        "      default_crossfade: 0.2",
        "      states:",
        "        - {name: idle, clip: animations/mannequin/idle.yaml}",
        "        - {name: walk, clip: animations/mannequin/walk.yaml}",
        "        - {name: run, clip: animations/mannequin/run.yaml}",
        "        - {name: jump, clip: animations/mannequin/jump.yaml, wrap: once}",
    ]
    lines += list(extra_components)
    lines.append("  children:")
    lines += emit_node(RIG, 4)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------------------------
# Clips
# ---------------------------------------------------------------------------------------------

PATHS = {
    "pelvis": "pelvis",
    "spine": "pelvis/spine",
    "chest": "pelvis/spine/chest",
    "head": "pelvis/spine/chest/neck/head",
}
for _s in "lr":
    PATHS[f"upper_arm_{_s}"] = f"pelvis/spine/chest/upper_arm_{_s}"
    PATHS[f"lower_arm_{_s}"] = f"pelvis/spine/chest/upper_arm_{_s}/lower_arm_{_s}"
    PATHS[f"thigh_{_s}"] = f"pelvis/thigh_{_s}"
    PATHS[f"shin_{_s}"] = f"pelvis/thigh_{_s}/shin_{_s}"
    PATHS[f"foot_{_s}"] = f"pelvis/thigh_{_s}/shin_{_s}/foot_{_s}"


def qmul(a, b):
    ax, ay, az, aw = a
    bx, by, bz, bw = b
    return [aw * bx + ax * bw + ay * bz - az * by,
            aw * by - ax * bz + ay * bw + az * bx,
            aw * bz + ax * by - ay * bx + az * bw,
            aw * bw - ax * bx - ay * by - az * bz]


def quat_xyz(x_deg, y_deg=0.0, z_deg=0.0):
    """Rotation X first, then Y, then Z (matches the Transform's Euler order)."""
    def axis(i, deg):
        a = math.radians(deg) * 0.5
        q = [0.0, 0.0, 0.0, math.cos(a)]
        q[i] = math.sin(a)
        return q
    return qmul(axis(2, z_deg), qmul(axis(1, y_deg), axis(0, x_deg)))


def rot_track(joint_name, samples, easing="linear"):
    """samples: [(time, (x_deg, y_deg, z_deg))]; keeps keys in one quaternion hemisphere."""
    keys, prev = [], None
    for t, angles in samples:
        q = quat_xyz(*angles)
        if prev is not None and sum(a * b for a, b in zip(q, prev)) < 0:
            q = [-c for c in q]
        prev = q
        keys.append((t, fmt([round(c, 6) for c in q])))
    return (PATHS[joint_name], "rotation_quat", keys, easing)


def pos_track(joint_name, channel, samples, easing="linear"):
    return (PATHS[joint_name], f"position.{channel}", [(t, num(v)) for t, v in samples], easing)


def write_clip(name, length, tracks, wrap="loop", events=(), root_motion=None):
    """events: [(time, name, string)]; root_motion: (object, translation, rotation) or None."""
    lines = [f"# mannequin {name}. {GENERATED}", "clip:", f"  name: {name}", f"  wrap: {wrap}",
             f"  length: {num(length)}"]
    if root_motion:
        obj, translation, rotation = root_motion
        lines.append(f"  root_motion: {{object: {obj}, translation: {translation}, rotation: {rotation}}}")
    if events:
        lines.append("  events:")
        for t, ev_name, ev_str in events:
            lines.append(f"    - {{time: {num(round(t, 4))}, name: {ev_name}, string: {ev_str}}}")
    lines.append("  tracks:")
    for path, prop, keys, easing in tracks:
        lines.append(f"    - object: {path}")
        lines.append(f"      property: {prop}")
        lines.append("      keys:")
        for t, v in keys:
            ease = "" if easing == "linear" else f", easing: {easing}"
            lines.append(f"        - {{time: {num(round(t, 4))}, value: {v}{ease}}}")
    os.makedirs(ANIM_DIR, exist_ok=True)
    with open(os.path.join(ANIM_DIR, f"{name}.yaml"), "w") as fh:
        fh.write("\n".join(lines) + "\n")


def cycle(length, n, fn):
    """n + 1 samples of fn(phase in [0, 1]) over one loop, the last equal to the first."""
    return [(length * i / n, fn((i % n) / n)) for i in range(n + 1)]


def gait(name, length, stride, knee, arm_swing, elbow, lean, bob, pelvis_z, travel, n=12):
    """A walk/run cycle: legs in antiphase, arms against the legs, knees bent during swing.

    The pelvis travels `travel` metres along +Y per cycle -- the clip's ROOT MOTION (pelvis, xy):
    the Animator holds the pelvis in place and hands the travel to its owner (a CharacterController
    with use_root_motion moves by it; anything else just plays the gait in place). A footstep
    event fires as each foot plants: the left thigh is furthest forward at phase 0.25, the right
    at 0.75.
    """
    tau = 2 * math.pi

    def thigh(phase, side):
        return stride * math.sin(tau * phase + (0 if side == "l" else math.pi))

    def shin(phase, side):
        p = tau * phase + (0 if side == "l" else math.pi)
        return -(5 + knee * max(0.0, math.cos(p)) ** 1.5)

    tracks = [pos_track("pelvis", "z", cycle(length, n, lambda p: pelvis_z - bob * math.cos(2 * tau * p))),
              pos_track("pelvis", "y", [(0.0, 0.0), (length, travel)])]
    tracks.append(rot_track("spine", cycle(length, n, lambda p: (-lean, 0, 0))))
    tracks.append(rot_track("chest", cycle(length, n, lambda p: (0, 0, 4 * math.sin(tau * p)))))
    tracks.append(rot_track("head", cycle(length, n, lambda p: (lean * 0.6, 0, -4 * math.sin(tau * p)))))
    for side in "lr":
        abduct = 7 if side == "l" else -7
        tracks.append(rot_track(f"thigh_{side}", cycle(length, n, lambda p, s=side: (thigh(p, s), 0, 0))))
        tracks.append(rot_track(f"shin_{side}", cycle(length, n, lambda p, s=side: (shin(p, s), 0, 0))))
        tracks.append(rot_track(f"foot_{side}", cycle(length, n,
                                                      lambda p, s=side: (-0.5 * (thigh(p, s) + shin(p, s)), 0, 0))))
        tracks.append(rot_track(f"upper_arm_{side}", cycle(length, n,
                                                           lambda p, s=side: (-arm_swing / stride * thigh(p, s), abduct, 0))))
        tracks.append(rot_track(f"lower_arm_{side}", cycle(length, n,
                                                           lambda p, s=side: (elbow + 0.3 * arm_swing / stride * max(0.0, -thigh(p, s)), 0, 0))))
    events = [(0.25 * length, "footstep", "left"), (0.75 * length, "footstep", "right")]
    write_clip(name, length, tracks, events=events, root_motion=("pelvis", "xy", "none"))


def idle():
    length, n, tau = 2.4, 8, 2 * math.pi
    breathe = lambda p: math.sin(tau * p)
    tracks = [
        pos_track("pelvis", "z", cycle(length, n, lambda p: 0.95 - 0.006 * (1 - breathe(p)))),
        rot_track("chest", cycle(length, n, lambda p: (-1.5 * breathe(p), 0, 0)), "ease_in_out"),
        rot_track("head", cycle(length, n, lambda p: (1.0 * breathe(p), 0, 3 * math.sin(tau * p * 0.5 * 2))), "ease_in_out"),
    ]
    for side in "lr":
        sgn = 1 if side == "l" else -1
        tracks.append(rot_track(f"upper_arm_{side}", cycle(length, n, lambda p, g=sgn: (2 * breathe(p), g * (7 + 1.5 * breathe(p)), 0)), "ease_in_out"))
        tracks.append(rot_track(f"lower_arm_{side}", cycle(length, n, lambda p: (12 + 2 * breathe(p), 0, 0)), "ease_in_out"))
        tracks.append(rot_track(f"thigh_{side}", cycle(length, n, lambda p: (2, 0, 0))))
        tracks.append(rot_track(f"shin_{side}", cycle(length, n, lambda p: (-4, 0, 0))))
        tracks.append(rot_track(f"foot_{side}", cycle(length, n, lambda p: (2, 0, 0))))
    write_clip("idle", length, tracks)


def jump():
    # Once: a quick tuck into the air pose, held. Played while airborne.
    key = lambda pose: [(0.0, pose[0]), (0.18, pose[1]), (0.5, pose[1])]
    tracks = [
        pos_track("pelvis", "z", [(0.0, 0.95), (0.18, 0.95), (0.5, 0.95)], "ease_out"),
        rot_track("spine", key([(0, 0, 0), (-8, 0, 0)]), "ease_out"),
        rot_track("head", key([(0, 0, 0), (6, 0, 0)]), "ease_out"),
    ]
    for side in "lr":
        sgn = 1 if side == "l" else -1
        lead = side == "l"
        tracks.append(rot_track(f"thigh_{side}", key([(2, 0, 0), (55 if lead else 15, 0, 0)]), "ease_out"))
        tracks.append(rot_track(f"shin_{side}", key([(-4, 0, 0), (-75 if lead else -40, 0, 0)]), "ease_out"))
        tracks.append(rot_track(f"foot_{side}", key([(2, 0, 0), (15, 0, 0)]), "ease_out"))
        tracks.append(rot_track(f"upper_arm_{side}", key([(0, sgn * 7, 0), (35 if lead else -25, sgn * 35, 0)]), "ease_out"))
        tracks.append(rot_track(f"lower_arm_{side}", key([(12, 0, 0), (45, 0, 0)]), "ease_out"))
    write_clip("jump", 0.5, tracks, wrap="once")


def main():
    os.makedirs(MESH_DIR, exist_ok=True)
    for name, (r, length) in PART_MESHES.items():
        capsule_mesh(os.path.join(MESH_DIR, f"{name}.yaml"), r, length)
    write_object()
    write_object(RAGDOLL_OBJECT_PATH, ragdoll_component(),
                 "With a Ragdoll: R (input_toggle) or Ragdoll::activate() goes limp, deactivate() recovers.")
    idle()
    # Travel per cycle ~ two foot strides (2 x 2 x leg 0.84 x sin(stride)): walk ~1.6 m/s, run ~5.3 m/s.
    gait("walk", 0.9, stride=26, knee=55, arm_swing=22, elbow=15, lean=3, bob=0.02, pelvis_z=0.94, travel=1.45)
    gait("run", 0.62, stride=44, knee=95, arm_swing=45, elbow=70, lean=12, bob=0.04, pelvis_z=0.9, travel=3.3)
    jump()
    print("wrote", OBJECT_PATH, "+", RAGDOLL_OBJECT_PATH, "+", len(PART_MESHES), "meshes + 4 clips")


if __name__ == "__main__":
    main()
