#!/usr/bin/env python3
"""Writes scenes/navigation/nav_demo/scene.yaml -- the navigation bench: A* agents across
two floors and a flow-field crowd chasing a moving target, on navmesh built from the colliders.

Layout (Z up, 40 x 40 m ground, x/y in [-20, 20]):
  * North-east -- the two-floor station (A*): a 10 x 10 m deck 3 m up (x, y in [6, 16]),
    reached by a 12-step staircase on its west side, a 27-degree ramp on its south side, and a
    one-way drop link off its east edge. A mud patch (area cost 8) sits across the direct
    approach to the stairs. Three couriers:
      courier_a  ground (SW of the mud) -> a point on the deck: detours around the mud, climbs.
      courier_b  chases `beacon`, which circles on the deck: re-plans as it moves.
      courier_c  deck -> ground east of the deck: takes the drop link instead of walking round.
  * South-west -- the flow station: `target` circles around a cluster of pillars; 144 mobs start
    in the north-west, behind a long wall, and follow one shared flow field toward it (rebuilt in
    the background each time the target moves half a metre).

Run:  python3 tools/gen_nav_demo_scene.py   then   ./build/toyengine nav_demo
"""

import math
import os

ASSETS = os.path.join(os.path.dirname(__file__), "..", "assets")
OUT = os.path.join(ASSETS, "scenes", "navigation", "nav_demo", "scene.yaml")


def v(x, y, z):
    return "{ x: %s, y: %s, z: %s }" % (fmt(x), fmt(y), fmt(z))


def fmt(f):
    s = "%.4f" % f
    s = s.rstrip("0")
    return s + "0" if s.endswith(".") else s


def transform(pos, rot=(0, 0, 0), scale=(1, 1, 1), indent=8):
    p = " " * indent
    return (f"{p}- type: Transform\n"
            f"{p}  position: {v(*pos)}\n"
            f"{p}  rotation: {v(*rot)}\n"
            f"{p}  scale: {v(*scale)}\n")


def block(name, pos, size, material, rot=(0, 0, 0), extra=""):
    """A box: a centred cube mesh scaled to `size`, with a unit BoxCollider (scales with it)."""
    return (f"    - name: {name}\n"
            f"      active: true\n"
            f"      components:\n"
            + transform(pos, rot, size) +
            f"        - type: MeshRenderer\n"
            f"          mesh_path: cube\n"
            f"          material: {material}\n"
            f"        - type: BoxCollider\n"
            f"          size: {v(1, 1, 1)}\n"
            f"          material: concrete\n"
            + extra +
            f"      children: []\n\n")


def agent(name, pos, color, nav, mesh_scale=1.0):
    """A capsule body (the shared `barrel`: radius 0.35, height 1.3, centred) standing on the
    surface: base_offset lifts its centre half its height above the floor."""
    h = 0.65 * mesh_scale
    return (f"    - name: {name}\n"
            f"      active: true\n"
            f"      components:\n"
            + transform((pos[0], pos[1], pos[2] + h), (0, 0, 0), (mesh_scale, mesh_scale, mesh_scale)) +
            f"        - type: MeshRenderer\n"
            f"          mesh_path: barrel\n"
            f"          material: {{ albedo: {{ r: {color[0]}, g: {color[1]}, b: {color[2]} }}, metallic: 0.0, roughness: 0.6, ao: 1.0 }}\n"
            f"        - type: NavAgent\n"
            f"          base_offset: {fmt(h)}\n"
            + "".join(f"          {k}: {val}\n" for k, val in nav) +
            f"      children: []\n\n")


def marker(name, pos, color, mover=""):
    return (f"    - name: {name}\n"
            f"      active: true\n"
            f"      components:\n"
            + transform(pos, (0, 0, 0), (0.35, 0.35, 0.35)) +
            f"        - type: MeshRenderer\n"
            f"          mesh_path: sphere\n"
            f"          material: {{ albedo: {{ r: {color[0]}, g: {color[1]}, b: {color[2]} }}, emissive: {{ r: {color[0]}, g: {color[1]}, b: {color[2]} }}, emissive_strength: 3.0, metallic: 0.0, roughness: 0.4, ao: 1.0 }}\n"
            + mover +
            f"      children: []\n\n")


def main():
    out = []
    out.append("""# nav_demo -- navigation bench: navmesh built from colliders, A* agents across two floors
# (stairs, ramp, one-way drop link, a costly mud area) and a 144-mob flow-field crowd chasing a
# moving target around obstacles.
#
# Run: ./build/toyengine nav_demo        (or SCENE=nav_demo)
# Generated by tools/gen_nav_demo_scene.py -- edit that, not this file.
#
# Map (Z up; ground x/y in [-20, 20]):
#   NE  deck (x, y in [6, 16], top z = 3): stairs on its west side (x 0..6, y 9.5..12.5),
#       ramp on its south side (x 9.5..12.5, y 0..6), drop link off its east edge to x = 17.5.
#       mud (cost 8, x -6..-1, y 6..16) blocks the straight approach to the stairs.
#       courier_a: ground (north of the mobs) -> deck, around the mud.  courier_b: chases `beacon` circling on the deck.
#       courier_c: deck -> ground east of it (takes the drop).
#   SW  `target` circles (-8, -8) at 6.5 m around five pillars; 144 mobs start NW, behind the
#       wall at y = -1.5, and follow its flow field.
#
# Overlay (scene settings `navigation.debug_draw`): cyan = walkable outline (mud edges in their
# own colour), orange = links, yellow = paths, green = flow arrows (every 4th cell).
# Worth sweeping: navigation.cell_size (0.25 / 0.5), agents[0].radius, the mud cost,
# flow.wall_penalty, debug_draw [Mesh, Grid] for the cell lattice.
scene:
  scene_name: nav_demo
  settings:
    navigation:
      cell_size: 0.25
      cell_height: 0.05
      agents:
        - { name: Humanoid, radius: 0.35, height: 1.8, max_climb: 0.3 }
      areas:
        - { name: Mud, cost: 8.0 }
      max_path_requests_per_frame: 32
      flow: { rebuild_distance: 0.5, wall_penalty: 1.0 }
      debug_draw: [Mesh, Links, Paths, Flow]
      debug_flow_stride: 4
  root_objects:
    # ============================================================================
    # GROUND -- the plane is a 2x2 quad: scale 20 -> 40 m. Its collider is a thin slab whose
    # top is the visible surface (z = 0).
    # ============================================================================
    - name: ground
      active: true
      components:
""")
    out.append(transform((0, 0, 0), (0, 0, 0), (20, 20, 1)))
    out.append("""        - type: MeshRenderer
          mesh_path: plane
          material: materials/prototype_grid
        - type: BoxCollider
          size: { x: 2.0, y: 2.0, z: 0.2 }
          center: { x: 0.0, y: 0.0, z: -0.1 }
          material: concrete
      children: []

    # ============================================================================
    # NORTH-EAST: TWO-FLOOR STATION (A*)
    # ============================================================================
""")
    # Deck: solid block, top at z = 3.
    out.append(block("deck", (11, 11, 1.5), (10, 10, 3), "materials/concrete"))
    # Stairs: 12 steps, 0.5 m run, 0.25 m rise, rising +X into the deck's west face.
    for i in range(12):
        top = 0.25 * (i + 1)
        out.append(block("stair_%02d" % i, (0.5 * i + 0.25, 11, top / 2), (0.5, 3, top), "materials/wood"))
    # Ramp: top surface from (y 0, z 0) to (y 6, z 3); a 0.4 m slab rotated about X.
    theta = math.atan2(3.0, 6.0)
    length = math.hypot(6.0, 3.0) + 0.3
    thick = 0.4
    n = (0.0, -math.sin(theta), math.cos(theta))
    c = (11.0, 3.0 - thick / 2 * n[1], 1.5 - thick / 2 * n[2])
    out.append(block("ramp", c, (3, length, thick), "materials/stone", rot=(math.degrees(theta), 0, 0)))
    # Low parapet on the deck's north edge (so the deck isn't just a slab) -- pure obstacle.
    out.append(block("parapet", (11, 15.8, 3.4), (8, 0.4, 0.8), "materials/brick",
                     extra="        - type: NavModifier\n          walkable: false\n"))
    # Drop link: one-way, deck east edge -> ground.
    out.append("""    - name: drop_link
      active: true
      components:
""" + transform((0, 0, 0)) + """        - type: NavLink
          start: { x: 15.5, y: 11.0, z: 3.0 }
          end: { x: 17.6, y: 11.0, z: 0.0 }
          bidirectional: false
          cost: 1.0
          snap_radius: 0.8
      children: []

""")
    # Mud: a NavVolume relabelling the ground (cost 8), plus a visible patch.
    out.append("""    - name: mud
      active: true
      components:
""" + transform((-3.5, 11, 0.01), (0, 0, 0), (2.5, 5, 1)) + """        - type: MeshRenderer
          mesh_path: plane
          material: { albedo: { r: 0.30, g: 0.21, b: 0.12 }, metallic: 0.0, roughness: 0.95, ao: 1.0 }
        - type: NavVolume
          size: { x: 2.0, y: 2.0, z: 1.0 }
          area: Mud
      children: []

""")
    out.append(marker("beacon", (11, 11, 3.6), (1.0, 0.75, 0.2),
                      "        - type: KinematicMover\n          mode: orbit\n          orbit_center: { x: 11.0, y: 11.0, z: 3.6 }\n"
                      "          orbit_radius: 3.0\n          speed: 25.0\n"))
    blue = (0.2, 0.45, 0.95)
    out.append(agent("courier_a", (-14, 17, 0), blue, [("speed", "3.0"), ("destination", v(7.5, 14.5, 3))], 1.2))
    out.append(agent("courier_b", (6, -14, 0), (0.25, 0.8, 0.9), [("speed", "3.5"), ("destination_object", "beacon")], 1.2))
    out.append(agent("courier_c", (8, 8, 3), (0.6, 0.35, 0.95), [("speed", "3.0"), ("destination", v(19, 13, 0))], 1.2))

    out.append("""    # ============================================================================
    # SOUTH-WEST: FLOW STATION -- a long wall (mobs spawn north of it) and five pillars the
    # target circles.
    # ============================================================================
""")
    out.append(block("wall", (-11, -1.5, 0.75), (16, 0.5, 1.5), "materials/brick"))
    for k, (px, py) in enumerate([(-11, -11), (-5, -11), (-11, -5), (-5, -5), (-8, -8)]):
        out.append(block("pillar_%d" % k, (px, py, 1.0), (1.2, 1.2, 2.0), "materials/stone"))
    out.append(marker("target", (-1.5, -8, 0.6), (1.0, 0.2, 0.2),
                      "        - type: KinematicMover\n          mode: orbit\n          orbit_center: { x: -8.0, y: -8.0, z: 0.6 }\n"
                      "          orbit_radius: 6.5\n          speed: 12.0\n"))
    red = (0.85, 0.25, 0.2)
    idx = 0
    for gy in range(12):
        for gx in range(12):
            x = -19.0 + gx * 0.95
            y = 1.5 + gy * 0.95
            shade = 0.75 + 0.25 * ((gx + gy) % 3) / 2.0
            out.append(agent("mob_%03d" % idx, (x, y, 0), (red[0] * shade, red[1] * shade, red[2] * shade),
                             [("speed", "3.2"), ("flow_target", "target")]))
            idx += 1

    out.append("""    # ============================================================================
    # CAMERA + LIGHT
    # ============================================================================
    - name: camera
      active: true
      components:
""" + transform((0, -29, 25), (50, 0, 0)) + """        - type: Camera
          main: true
          projection: Perspective
          fov: 55.0
          near_clip_plane: 0.1
          far_clip_plane: 500.0
        - type: CameraController
          mode: orbit
          target: { x: 0.0, y: 0.0, z: 0.0 }
          min_distance: 5.0
          max_distance: 90.0
      children: []

    - name: sun
      active: true
      components:
""" + transform((0, 0, 30)) + """        - type: DirectionalLight
          direction: { x: -0.35, y: 0.4, z: -0.85 }
          color: { r: 1.0, g: 0.96, b: 0.9 }
          intensity: 1.0
          cast_shadows: true
      children: []
""")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("".join(out))
    print("wrote", os.path.relpath(OUT, ASSETS), "--", idx, "mobs")


if __name__ == "__main__":
    main()
