#!/usr/bin/env python3
"""Writes assets/scenes/gameplay/character_demo: the CharacterController bench.

Outputs (under the scene folder):
  * scene.yaml -- the player (a mannequin instance with CharacterController +
    CharacterAnimDriver), a third-person orbit camera that collides, and one station per motor
    feature (see the scene header).
  * meshes/character_terrain.yaml + character_terrain_collider.yaml -- a bumpy heightfield patch
    (render mesh and its MeshCollider copy).

Run:  python3 tools/gen_character_demo_scene.py   then   ./build/toyengine character_demo
"""

import math
import pathlib
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mesh_yaml  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "scenes", "gameplay",
                    "character_demo")
GENERATED = "GENERATED by tools/gen_character_demo_scene.py; edit that, not this file."

GRID = "materials/prototype_grid"


def num(x):
    return f"{x:.6g}"


def v3(x, y, z):
    return f"{{ x: {num(x)}, y: {num(y)}, z: {num(z)} }}"


def tint(r, g, b):
    return f"{{ base: {GRID}, albedo: {{ r: {num(r)}, g: {num(g)}, b: {num(b)} }} }}"


def block(name, pos, size, material, rot=(0, 0, 0), extra=(), comment=None):
    """A centred cube of `size` with a matching BoxCollider (static unless `extra` says otherwise)."""
    lines = []
    if comment:
        lines += [f"    # {c}" for c in comment.split("\n")]
    lines += [
        f"    - name: {name}",
        "      components:",
        "        - type: Transform",
        f"          position: {v3(*pos)}",
        f"          rotation: {v3(*rot)}",
        f"          scale: {v3(*size)}",
        "        - type: MeshRenderer",
        "          mesh_path: cube",
        f"          material: {material}",
        "        - type: BoxCollider",
        "          size: { x: 1.0, y: 1.0, z: 1.0 }",
    ]
    for e in extra:
        lines.append(f"        {e}")
    lines.append("      children: []")
    lines.append("")
    return lines


def ramp(name, x, y0, angle, length, width, material, comment):
    """A 0.2 m slab rising toward +Y at `angle` degrees, its lower top edge on the ground at y0."""
    t = math.radians(angle)
    cy = y0 + 0.5 * length * math.cos(t) + 0.1 * math.sin(t)
    cz = 0.5 * length * math.sin(t) - 0.1 * math.cos(t)
    return block(name, (x, cy, cz), (width, length, 0.2), material, rot=(angle, 0, 0), comment=comment)


def ragdoll_station(ox):
    """The ragdoll bench at x = ox: a top landing 2.4 m up, 8 steps descending toward +Y, three
    limp mannequin_ragdolls shoved down them, and a kinematic ram sweeping the landing below."""
    steps, rise, run = 8, 0.3, 0.55
    top_z, y0, width = steps * rise, -4.0, 6.0
    stair = tint(0.55, 0.6, 0.7)
    L = block("ragdoll_landing", (ox, y0 - 2.0, top_z / 2), (width, 4.0, top_z), stair,
              comment=f"Ragdolls: a top landing {num(top_z)} m up and {steps} steps down toward +Y.")
    for i in range(steps):
        h = top_z - (i + 1) * rise
        if h <= 0:
            continue
        L += block(f"ragdoll_step_{i + 1}", (ox, y0 + (i + 0.5) * run, h / 2), (width, run, h), stair)
    for k, dx in enumerate((-1.8, 0.0, 1.8)):
        if k == 0:
            L.append("    # Tumblers: limp from the first frame (mode: ragdoll), shoved down the stairs.")
        L += [
            f"    - name: tumbler_{k + 1}",
            "      prefab: objects/mannequin_ragdoll",
            "      components:",
            "        - type: Transform",
            f"          position: {v3(ox + dx, y0 - 0.6, top_z)}",
            f"          rotation: {v3(0, 0, 180 if k == 1 else 0)}",
            f"          scale: {v3(1, 1, 1)}",
            "        - type: Ragdoll",
            "          mode: ragdoll",
            f"          start_impulse: {v3(30 * (k - 1), 280 + 40 * k, 140)}",
            "",
        ]
    land_y = y0 + steps * run + 1.6
    L += block("ragdoll_ram", (ox, land_y, 0.45), (0.8, 3.0, 0.9), "{ albedo: { r: 0.85, g: 0.3, b: 0.15 }, roughness: 0.5 }",
               extra=["- type: Rigidbody", "  is_kinematic: true", "  use_gravity: false",
                      "- type: KinematicMover", "  mode: pingpong", f"  axis: {v3(1, 0, 0)}", "  distance: 7.0",
                      "  speed: 0.1"],
               comment="The ram: a kinematic block ping-ponging along X across the landing at the stairs' foot.")
    return L


def terrain_mesh():
    """A 12 x 12 m patch of gentle hills (slopes under ~35 degrees), zero at its rim."""
    n, size = 32, 12.0
    verts, uvs, faces = [], [], []
    for j in range(n + 1):
        for i in range(n + 1):
            x = -size / 2 + size * i / n
            y = -size / 2 + size * j / n
            u, v = i / n, j / n
            w = math.sin(math.pi * u) * math.sin(math.pi * v)          # 0 at the rim
            f = 0.5 + 0.5 * math.sin(0.55 * x + 0.4) * math.cos(0.5 * y - 0.3)
            f = 0.75 * f + 0.25 * (0.5 + 0.5 * math.sin(1.1 * x + 0.7 * y))
            verts.append([round(x, 5), round(y, 5), round(0.01 + 1.4 * w * f, 5)])
            uvs.append([round(x * 0.5, 5), round(y * 0.5, 5)])
    row = n + 1
    for j in range(n):
        for i in range(n):
            a = j * row + i
            faces.append([a, a + 1, a + row + 1, a + row])
    os.makedirs(os.path.join(ROOT, "meshes"), exist_ok=True)
    # Rounded to 5 decimals, as the editor saves them, so a re-save draws the identical mesh.
    r5 = lambda vs: [[round(c, 5) for c in v] for v in vs]
    normals = r5(mesh_yaml.vertex_normals(verts, faces))
    mesh_yaml.write_mesh(pathlib.Path(ROOT, "meshes", "character_terrain.yaml"), verts, faces, uvs, normals=normals,
                         tangents=r5(mesh_yaml.perpendicular_tangents(normals)))
    with open(os.path.join(ROOT, "meshes", "character_terrain_collider.yaml"), "w") as fh:
        fh.write(f"# Collision copy of character_terrain (a MeshCollider needs its own file). {GENERATED}\n")
        fh.write("vertices:\n" + "".join(f"  - {mesh_yaml.fmt_vec(p)}\n" for p in verts))
        fh.write("faces:\n" + "".join(f"  - {f}\n" for f in faces))


HEADER = f"""# character_demo -- the CharacterController bench: a mannequin player with a third-person
# camera, and one station per character-motor feature.
# {GENERATED}
#
# Run: ./build/toyengine character_demo        (or SCENE=character_demo)
# Controls: WASD move (camera-relative), Space jump, LeftShift sprint, mouse orbits the camera,
# scroll zooms. The camera pulls in when a wall blocks the view of the player.
#
# Map (the player starts at the origin facing +Y; stations ahead of it):
#   x = -10  stairs         8 steps of 0.25 m (under step_height 0.35: walked up), to a deck
#   x =  -6  tall step      one 0.5 m block (over step_height: blocked; jump onto it)
#   x =  -2  walkable ramp  25 degrees, to a deck
#   x =   2  steep ramp     55 degrees (over slope_limit 45: a wall; you slide off it)
#   x =   6  moving deck    0.3 m kinematic platform, ping-ponging along Y: step on, ride
#   x =  10  crates         dynamic boxes the player pushes
#   x = -14  low ceiling    a roof at 2.3 m: jumping under it bumps the head
#   y =  16  terrain        a bumpy MeshCollider heightfield patch (walk over it)
#   y = -10  camera wall    a wall behind the start camera: walk back toward it and the camera pulls in
#   x =  -3  foot IK        an idle mannequin with one foot on a 0.2 m block: FootIK plants both feet
#   y =  -4  coins          five spinning coins to pick up (SaveDemo)
#   x =  24  ragdolls       three limp mannequin_ragdolls shoved down a flight of 8 stairs (from
#                           y = -8 up top), and a kinematic ram sweeping the landing at its foot
#
# R toggles the player's Ragdoll: it goes limp with a backward shove, and R again blends it back
# into idle where the body lies (the CharacterController's capsule switches off meanwhile).
# Worth checking: physics debug draw (joints: anchors + cone-twist cones), the bodies settling.
#
# Save / load (toyengine/save/): F5 quick-saves, F9 quick-loads. The save holds the player's pose
# (its SaveId + CharacterController, an ISaveable), the collected coins and the weather clock
# (SaveDemo's on_save / on_load hooks). The clock runs a 6-minute day so a load visibly rewinds it.
#
# The player moves by ROOT MOTION: the walk / run clips' pelvis travel (Animator apply_root_motion
# -> CharacterController use_root_motion), so its speed is the clip's (walk ~1.6 m/s, sprint to run
# ~5.3 m/s); input steers. FootIK keeps its feet on stairs and slopes while grounded, and the walk /
# run clips fire `footstep` events (scene EventBus "anim_event").
"""


def main():
    terrain_mesh()
    L = [HEADER.rstrip("\n"), "scene:", "  scene_name: character_demo",
         "  settings:",
         "    # The weather clock the save demo stores (clear sky; a 6-minute day).",
         "    weather:",
         "      enabled: true",
         "      time_of_day: 10.0",
         "      day_length_minutes: 6",
         "      drive_sun: true",
         "      condition: clear",
         "      schedule: fixed",
         "  root_objects:"]

    L += [
        "    # Ground: a 60 x 60 m slab, its top at z = 0.",
        "    - name: ground",
        "      components:",
        "        - type: Transform",
        f"          position: {v3(0, 0, -0.25)}",
        f"          rotation: {v3(0, 0, 0)}",
        f"          scale: {v3(60, 60, 0.5)}",
        "        - type: MeshRenderer",
        "          mesh_path: cube",
        f"          material: {tint(0.55, 0.57, 0.6)}",
        "        - type: BoxCollider",
        "          size: { x: 1.0, y: 1.0, z: 1.0 }",
        "      children: []",
        "",
    ]

    # Player.
    L += [
        "    # The player: the mannequin prefab plus a CharacterController (it adds its own kinematic",
        "    # Rigidbody + CapsuleCollider) and the demo CharacterAnimDriver (idle/walk/run/jump). It",
        "    # moves by root motion (the Animator override + use_root_motion) and plants its feet (FootIK).",
        "    - name: player",
        "      prefab: objects/mannequin_ragdoll",
        "      components:",
        "        - type: Transform",
        f"          position: {v3(0, 0, 0)}",
        f"          rotation: {v3(0, 0, 0)}",
        f"          scale: {v3(1, 1, 1)}",
        "        - type: CharacterController",
        "          radius: 0.3",
        "          height: 1.8",
        "          step_height: 0.35",
        "          slope_limit: 45.0",
        "          move_speed: 3.0",
        "          sprint_multiplier: 2.0",
        "          jump_height: 1.2",
        "          use_root_motion: true",
        "        - type: Animator",
        "          apply_root_motion: true",
        "        - type: CharacterAnimDriver",
        "          walk_speed: 0.2",
        "          run_speed: 4.0",
        "          crossfade: 0.2",
        "        - type: FootIK",
        "          ray_up: 0.45",
        "          ray_down: 0.4",
        "        # R goes limp (shoved backward) and recovers; linked to the CharacterController.",
        "        - type: Ragdoll",
        "          input_toggle: true",
        "          toggle_impulse: { x: 0, y: -60, z: 20 }",
        "          blend_time: 0.6",
        "        # Saves the CharacterController's pose (an ISaveable) under objects/player.",
        "        - type: SaveId",
        "          id: player",
        "",
    ]

    # Save demo: coins the player picks up, remembered (with the clock) by SaveDemo's save hooks.
    L += [
        "    # Save demo (F5 save / F9 load): SaveDemo picks up the coin_* objects and keeps the",
        "    # collected set and the weather clock in the save's global section.",
        "    - name: save_demo",
        "      components:",
        "        - type: Transform",
        f"          position: {v3(0, 0, 0)}",
        f"          rotation: {v3(0, 0, 0)}",
        f"          scale: {v3(1, 1, 1)}",
        "        - type: SaveDemo",
        "          coin_prefix: coin_",
        "          pickup_radius: 1.0",
        "      children: []",
        "",
    ]
    for i, x in enumerate((-6, -3, 0, 3, 6)):
        L += [
            f"    - name: coin_{i + 1}",
            "      components:",
            "        - type: Transform",
            f"          position: {v3(x, -4, 0.9)}",
            f"          rotation: {v3(0, 0, 0)}",
            f"          scale: {v3(0.5, 0.12, 0.5)}",
            "        - type: MeshRenderer",
            "          mesh_path: cube",
            "          material: { albedo: { r: 1.0, g: 0.78, b: 0.2 }, metallic: 1.0, roughness: 0.3 }",
            "        - type: KinematicMover",
            "          mode: spin",
            f"          spin_axis: {v3(0, 0, 1)}",
            "          spin_speed: 120.0",
            "      children: []",
            "",
        ]

    # Foot IK demo: an idle mannequin facing the start camera, its right foot over a 0.2 m block.
    L += block("foot_ik_block", (-3.2, 1.5, 0.1), (0.5, 0.8, 0.2), tint(0.85, 0.7, 0.35),
               comment="Foot IK: a 0.2 m block under the demo mannequin's right foot (it faces -Y, so its right is -X).")
    L += [
        "    - name: foot_ik_demo",
        "      prefab: objects/mannequin",
        "      components:",
        "        - type: Transform",
        f"          position: {v3(-3.0, 1.5, 0)}",
        f"          rotation: {v3(0, 0, 180)}",
        f"          scale: {v3(1, 1, 1)}",
        "        - type: FootIK",
        "          blend_speed: 0",
        "",
    ]

    # Stairs: 8 x 0.25 m risers, 0.4 m treads, from y = 4; a deck at the top.
    rise, tread, steps = 0.25, 0.4, 8
    for i in range(steps):
        h = rise * (i + 1)
        L += block(f"stair_{i + 1}", (-10, 4 + tread * i + tread / 2, h / 2), (2.4, tread, h), tint(0.75, 0.62, 0.45),
                   comment="Stairs: 0.25 m risers (under step_height), walked straight up." if i == 0 else None)
    top = rise * steps
    L += block("stair_deck", (-10, 4 + tread * steps + 1.5, top / 2), (2.4, 3.0, top), tint(0.75, 0.62, 0.45))

    L += block("tall_step", (-6, 5.5, 0.25), (2.4, 3.0, 0.5), tint(0.85, 0.45, 0.4),
               comment="Tall step: 0.5 m, over step_height -- blocks walking, a jump clears it.")

    ramp_len = 5.0
    L += ramp("ramp_walkable", -2, 4, 25, ramp_len, 2.4, tint(0.45, 0.75, 0.5),
              "Walkable ramp: 25 degrees (under slope_limit 45) -- walked up, and snapped to on the way down.")
    deck_h = ramp_len * math.sin(math.radians(25))
    L += block("ramp_deck", (-2, 4 + ramp_len * math.cos(math.radians(25)) + 1.0, deck_h / 2), (2.4, 2.0, deck_h),
               tint(0.45, 0.75, 0.5))
    L += ramp("ramp_steep", 2, 4, 55, 4.0, 2.4, tint(0.85, 0.45, 0.4),
              "Steep ramp: 55 degrees (over slope_limit) -- acts as a wall; dropped onto it, you slide off.")

    L += block("moving_deck", (6, 6, 0.15), (2.5, 2.5, 0.3), tint(0.4, 0.6, 0.9),
               extra=["- type: Rigidbody", "  is_kinematic: true", "  use_gravity: false",
                      "- type: KinematicMover", "  mode: pingpong", f"  axis: {v3(0, 1, 0)}", "  distance: 5.0",
                      "  speed: 0.12"],
               comment="Moving deck: a 0.3 m kinematic platform (step onto it) that ping-pongs 5 m along Y.")

    for i, (dx, dy, s, m) in enumerate([(0, 4.5, 0.8, 12.0), (1.2, 6.0, 0.8, 12.0), (-0.6, 7.5, 1.0, 30.0)]):
        L += block(f"crate_{i + 1}", (10 + dx, dy, s / 2), (s, s, s), "materials/wood_crate",
                   extra=["- type: Rigidbody", f"  mass: {num(m)}", "  use_gravity: true", "  is_kinematic: false"],
                   comment="Crates: dynamic boxes (12-30 kg) the player pushes." if i == 0 else None)

    L += block("ceiling_roof", (-14, 6, 2.45), (3.0, 3.0, 0.3), tint(0.6, 0.6, 0.65),
               comment="Low ceiling: a roof slab with its underside at 2.3 m on two posts; jump under it.")
    for i, px in enumerate((-15.35, -12.65)):
        L += block(f"ceiling_post_{i + 1}", (px, 6, 1.15), (0.3, 3.0, 2.3), tint(0.6, 0.6, 0.65))

    L += block("camera_wall", (0, -10, 2.0), (10, 0.4, 4.0), tint(0.7, 0.7, 0.72),
               comment="Camera wall: back the player toward it and the orbit camera pulls in rather than clipping.")

    L += [
        "    # Terrain: a bumpy 12 x 12 m heightfield on a static MeshCollider.",
        "    - name: terrain_patch",
        "      components:",
        "        - type: Transform",
        f"          position: {v3(0, 18, 0)}",
        f"          rotation: {v3(0, 0, 0)}",
        f"          scale: {v3(1, 1, 1)}",
        "        - type: MeshRenderer",
        "          mesh_path: character_terrain",
        f"          material: {tint(0.5, 0.68, 0.42)}",
        "        - type: MeshCollider",
        "          mesh_path: character_terrain_collider",
        "          convex: false",
        "      children: []",
        "",
    ]

    L += ragdoll_station(24.0)

    L += [
        "    # Third-person camera: orbits the player and collides (pulls in when blocked).",
        "    - name: camera",
        "      components:",
        "        - type: Transform",
        f"          position: {v3(0, -8, 4.5)}",
        f"          rotation: {v3(65, 0, 0)}",
        f"          scale: {v3(1, 1, 1)}",
        "        - type: Camera",
        "          main: true",
        "          projection: Perspective",
        "          fov: 60.0",
        "          near_clip_plane: 0.1",
        "          far_clip_plane: 400.0",
        "        - type: CameraController",
        "          mode: orbit",
        "          tracker: player",
        f"          target_offset: {v3(0, 0, 1.4)}",
        "          follow_smoothing: 12.0",
        "          movement_smoothing: 0.2",
        "          mouse_sensitivity: 0.12",
        "          distance: 9.0",
        "          yaw_deg: 0.0",
        "          pitch_deg: 24.0",
        "          min_pitch_deg: -10.0",
        "          max_pitch_deg: 80.0",
        "          min_distance: 1.5",
        "          max_distance: 20.0",
        "          collide: true",
        "          collision_radius: 0.25",
        "      children: []",
        "",
        "    - name: sun",
        "      components:",
        "        - type: Transform",
        f"          position: {v3(0, 0, 20)}",
        f"          rotation: {v3(0, 0, 0)}",
        f"          scale: {v3(1, 1, 1)}",
        "        - type: DirectionalLight",
        f"          direction: {v3(-0.45, 0.55, -0.7)}",
        "          color: { r: 1.0, g: 0.96, b: 0.9 }",
        "          intensity: 1.0",
        "          cast_shadows: true",
        "      children: []",
    ]
    os.makedirs(ROOT, exist_ok=True)
    with open(os.path.join(ROOT, "scene.yaml"), "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote", os.path.join(ROOT, "scene.yaml"))


if __name__ == "__main__":
    main()
