#!/usr/bin/env python3
"""Writes assets/scenes/tests/water/water_stress/scene.yaml -- a large-world benchmark for toyengine/water.

  * a 1 km procedural ocean (512 quads a side) over a flat static seabed;
  * three lakes 650-860 m from the camera, each over its own bed;
  * 200 buoyant crates: 50 around the camera, the rest scattered over the far ocean and lakes.

Run headless per water_quality tier and compare the profiles (see toyengine/water/README.md):

    HEADLESS=1 PROFILE=out_high.csv MAX_FRAMES=600 ./build/toyengine water_stress

Deterministic: a fixed seed, so every run places the crates identically.
"""

import math
import os
import random

OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "scenes", "tests", "water", "water_stress", "scene.yaml")

WATER_MATERIAL = """          material: materials/water"""


def water(name, x, y, size, res, amp, length):
    return f"""    - name: {name}
      active: true
      components:
        - type: Transform
          position: {{ x: {x}, y: {y}, z: 0.0 }}
        - type: MeshRenderer
          affects_reflection_probes: false
{WATER_MATERIAL}
        - type: WaterBody
          mode: planar
          size: {{ x: {size}, y: {size} }}
          resolution: {res}
          wave_amplitude: {amp}
          wave_length: {length}
          wave_direction: 30.0
          wave_steepness: 0.55
          max_depth: 20.0
      children: []
"""


def bed(name, x, y, size, depth):
    return f"""    - name: {name}
      active: true
      components:
        - type: Transform
          position: {{ x: {x}, y: {y}, z: {-depth - 0.5} }}
          scale: {{ x: {size}, y: {size}, z: 1.0 }}
        - type: MeshRenderer
          mesh_path: cube
          material: materials/sand
        - type: BoxCollider
          size: {{ x: 1.0, y: 1.0, z: 1.0 }}
      children: []
"""


def crate(i, x, y, mass):
    return f"""    - name: crate_{i:03d}
      active: true
      components:
        - type: Transform
          position: {{ x: {x:.2f}, y: {y:.2f}, z: 1.5 }}
          rotation: {{ x: 10.0, y: 20.0, z: {(i * 37) % 360}.0 }}
        - type: MeshRenderer
          mesh_path: cube
          material: materials/wood_crate
        - type: BoxCollider
          size: {{ x: 1.0, y: 1.0, z: 1.0 }}
        - type: Rigidbody
          mass: {mass:.0f}
        - type: Buoyancy
      children: []
"""


def main():
    rng = random.Random(7)
    lakes = [("lake_east", 650.0, 0.0), ("lake_north", 0.0, 760.0), ("lake_southwest", -700.0, -500.0)]
    parts = ["""# water_stress -- a large-world benchmark for toyengine/water. GENERATED by
# tools/gen_water_stress_scene.py; edit that, not this file.
#
#   * a 1 km procedural ocean (512 quads a side), three lakes 650-860 m away;
#   * 200 buoyant crates: 50 around the camera, 150 scattered far out.
#
# What it shows per water_quality tier: how many floaters get full buoyancy (the rest are frozen
# out of range), how the ocean's render tiles cull and LOD, and the stage-2 bake budget.
format: blender
scene:
  scene_name: water_stress
  root_objects:
"""]
    parts.append(water("ocean", 0.0, 0.0, 1000.0, 512, 0.35, 14.0))
    parts.append(bed("ocean_bed", 0.0, 0.0, 1000.0, 8.0))
    for name, x, y in lakes:
        parts.append(water(name, x, y, 80.0, 128, 0.12, 6.0))
        parts.append(bed(name + "_bed", x, y, 80.0, 4.0))
    i = 0
    for _ in range(50):  # around the camera
        parts.append(crate(i, rng.uniform(-30, 30), rng.uniform(-30, 30), rng.uniform(250, 600)))
        i += 1
    for _ in range(90):  # far ocean
        r = rng.uniform(150, 480)
        a = rng.uniform(0, 6.2831853)

        parts.append(crate(i, r * math.cos(a), r * math.sin(a), rng.uniform(250, 600)))
        i += 1
    for k in range(60):  # the lakes
        _, lx, ly = lakes[k % 3]
        parts.append(crate(i, lx + rng.uniform(-30, 30), ly + rng.uniform(-30, 30), rng.uniform(250, 600)))
        i += 1
    parts.append("""    - name: camera
      active: true
      components:
        - type: Transform
          position: { x: 0.0, y: -40.0, z: 18.0 }
        - type: Camera
          main: true
          projection: Perspective
          fov: 55.0
          near_clip_plane: 0.3
          far_clip_plane: 2000.0
        - type: CameraController
          mode: orbit
          target: { x: 0.0, y: 0.0, z: 0.0 }
          distance: 45.0
          yaw_deg: 0.0
          pitch_deg: 18.0
          movement_smoothing: 0.25
          min_distance: 4.0
          max_distance: 900.0
          min_pitch_deg: 2.0
          max_pitch_deg: 85.0
          capture_cursor: true
      children: []

    - name: sun
      active: true
      components:
        - type: Transform
          position: { x: 0.0, y: 0.0, z: 40.0 }
        - type: DirectionalLight
          direction: { x: -0.4, y: 0.35, z: -0.85 }
          color: { r: 1.0, g: 0.95, b: 0.86 }
          intensity: 1.2
          cast_shadows: true
          shadow_intensity: 1.0
      children: []

    - name: sky
      active: true
      components:
        - type: Transform
          position: { x: 0.0, y: 0.0, z: 0.0 }
        - type: EnvironmentLight
          sky_color: { r: 0.48, g: 0.64, b: 0.9 }
          ground_color: { r: 0.2, g: 0.18, b: 0.14 }
          sky_intensity: 1.0
      children: []
""")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("".join(parts))
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
