#!/usr/bin/env python3
"""Writes assets/scenes/gameplay/loading_demo: async scene loading + SceneLink transitions.

Outputs (under the scene folder):
  * scene.yaml -- the light "hub": a player, a camera and two doorways. Walking through the
    north door loads heavy.yaml behind the loading screen (ui/loading_screen); the east door
    loads it with a plain fade.
  * heavy.yaml -- the heavy level: a 34 x 34 grid of towers (over a thousand root objects,
    built a batch per frame), a ring of animated mannequins, and a door back to the hub.

Both are ordinary scenes: `./build/toyengine loading_demo` starts in the hub. The SceneLink
spawn points put the player in front of the door it came through, facing away from it.

Run:  python3 tools/gen_loading_demo_scene.py   then   ./build/toyengine loading_demo
"""

import math
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "scenes", "gameplay",
                    "loading_demo")
GENERATED = "GENERATED by tools/gen_loading_demo_scene.py; edit that, not this file."
GRID = "materials/prototype_grid"


def num(x):
    return f"{x:.6g}"


def v3(x, y, z):
    return f"{{ x: {num(x)}, y: {num(y)}, z: {num(z)} }}"


def tint(r, g, b):
    return f"{{ base: {GRID}, albedo: {{ r: {num(r)}, g: {num(g)}, b: {num(b)} }} }}"


def box(name, pos, scale, color, collider=True, rot=(0, 0, 0), mesh="cube"):
    lines = [
        f"    - name: {name}",
        "      components:",
        "        - type: Transform",
        f"          position: {v3(*pos)}",
        f"          rotation: {v3(*rot)}",
        f"          scale: {v3(*scale)}",
        "        - type: MeshRenderer",
        f"          mesh_path: {mesh}",
        f"          material: {tint(*color)}",
    ]
    if collider:
        lines += ["        - type: BoxCollider", "          size: { x: 1.0, y: 1.0, z: 1.0 }"]
    return "\n".join(lines) + "\n"


def marker(name, pos, yaw):
    return (f"    - name: {name}\n"
            "      components:\n"
            "        - type: Transform\n"
            f"          position: {v3(*pos)}\n"
            f"          rotation: {v3(0, 0, yaw)}\n"
            "          scale: { x: 1, y: 1, z: 1 }\n")


def player(pos, yaw):
    return f"""    # The player: the mannequin prefab with a CharacterController (WASD, Space, LeftShift).
    - name: player
      prefab: objects/mannequin
      components:
        - type: Transform
          position: {v3(*pos)}
          rotation: {v3(0, 0, yaw)}
          scale: {{ x: 1, y: 1, z: 1 }}
        - type: CharacterController
          radius: 0.3
          height: 1.8
          move_speed: 4.0
          sprint_multiplier: 2.0
        - type: CharacterAnimDriver
          walk_speed: 0.2
          run_speed: 5.0
"""


def camera(dist=9.0, pitch=26.0):
    return f"""    - name: camera
      components:
        - type: Transform
          position: {{ x: 0, y: -8, z: 4.5 }}
          rotation: {{ x: 65, y: 0, z: 0 }}
          scale: {{ x: 1, y: 1, z: 1 }}
        - type: Camera
          main: true
          projection: Perspective
          fov: 60.0
          near_clip_plane: 0.1
          far_clip_plane: 400.0
        - type: CameraController
          mode: orbit
          tracker: player
          target_offset: {{ x: 0, y: 0, z: 1.4 }}
          follow_smoothing: 12.0
          mouse_sensitivity: 0.12
          distance: {num(dist)}
          yaw_deg: 0.0
          pitch_deg: {num(pitch)}
          min_pitch_deg: -10.0
          max_pitch_deg: 80.0
          min_distance: 1.5
          max_distance: 30.0
          collide: true
"""


def sun():
    return """    - name: sun
      components:
        - type: Transform
          position: { x: 0, y: 0, z: 20 }
          rotation: { x: 0, y: 0, z: 0 }
          scale: { x: 1, y: 1, z: 1 }
        - type: DirectionalLight
          direction: { x: -0.45, y: 0.55, z: -0.7 }
          color: { r: 1.0, g: 0.96, b: 0.9 }
          intensity: 1.0
          cast_shadows: true
"""


def doorway(name, center, along_x, color, link):
    """Two posts and a lintel around a SceneLink trigger box. `along_x`: the opening spans X."""
    cx, cy = center
    out = ""
    span = 1.6
    for i, s in enumerate((-1, 1)):
        px, py = (cx + s * span, cy) if along_x else (cx, cy + s * span)
        out += box(f"{name}_post_{i}", (px, py, 1.5), (0.5, 0.5, 3.0), color)
    lw = (span * 2 + 0.5, 0.5, 0.5) if along_x else (0.5, span * 2 + 0.5, 0.5)
    out += box(f"{name}_lintel", (cx, cy, 3.25), lw, color)
    size = "{ x: 2.6, y: 1.2, z: 3.0 }" if along_x else "{ x: 1.2, y: 2.6, z: 3.0 }"
    out += (f"    - name: {name}_link\n"
            "      components:\n"
            "        - type: Transform\n"
            f"          position: {v3(cx, cy, 1.5)}\n"
            "          rotation: { x: 0, y: 0, z: 0 }\n"
            "          scale: { x: 1, y: 1, z: 1 }\n"
            "        - type: SceneLink\n"
            + "".join(f"          {k}: {v}\n" for k, v in link.items())
            + f"          size: {size}\n")
    return out


def ground(size, color):
    return box("ground", (0, 0, -0.25), (size, size, 0.5), color)


def write(name, text):
    path = os.path.join(ROOT, name)
    with open(path, "w") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(path)}")


def hub():
    out = f"""# loading_demo (hub) -- async scene loading and SceneLink transitions.
# {GENERATED}
#
# Run: ./build/toyengine loading_demo
# Walk (WASD) through the NORTH door (blue, y = 8): heavy.yaml loads in the background behind the
# loading screen (ui/loading_screen: a progress bar and a status line). Through the EAST door
# (orange, x = 8) it loads behind a plain fade. Either way this scene keeps running until the
# heavy one is built and its assets are in; heavy.yaml's door brings you back here.
scene:
  scene_name: loading_demo
  root_objects:
"""
    out += ground(40, (0.55, 0.57, 0.6))
    out += player((0, 0, 0), 0)
    out += marker("arrive_from_heavy", (0, 5.5, 0), 180)
    out += doorway("north_door", (0, 8), True, (0.3, 0.45, 0.85), {
        "target_scene": "heavy.yaml",
        "transition": "loading_screen",
        "loading_screen": "ui/loading_screen",
        "fade_time": 0.3,
        "min_display_time": 1.0,
        "spawn_point": "arrive_from_hub",
    })
    out += doorway("east_door", (8, 0), False, (0.9, 0.55, 0.25), {
        "target_scene": "heavy.yaml",
        "transition": "fade",
        "fade_time": 0.4,
        "spawn_point": "arrive_from_hub",
    })
    # A few props so the hub is not empty.
    for i in range(6):
        a = i / 6 * math.tau + 0.4
        out += box(f"pillar_{i}", (math.cos(a) * 12, math.sin(a) * 12, 1.0), (0.8, 0.8, 2.0), (0.7, 0.68, 0.62))
    out += camera()
    out += sun()
    write("scene.yaml", out)


def heavy():
    n = 34
    spacing = 3.0
    out = f"""# loading_demo (heavy) -- the level the hub's doors load: {n * n} towers, built a batch of root
# objects per frame while the hub keeps running, plus a ring of animated mannequins.
# {GENERATED}
#
# Its door (green, west of the start) goes back to the hub with a fade.
scene:
  scene_name: loading_demo_heavy
  root_objects:
"""
    half = (n - 1) * spacing / 2
    out += ground(n * spacing + 20, (0.42, 0.5, 0.4))
    out += player((0, 0, 0), 0)
    out += marker("arrive_from_hub", (0, 0, 0), 0)
    out += doorway("back_door", (-6, 0), False, (0.35, 0.75, 0.4), {
        "target_scene": "scene.yaml",
        "transition": "fade",
        "fade_time": 0.4,
        "spawn_point": "arrive_from_heavy",
    })
    # Towers on a grid, leaving a clearing around the start for the player and the ring.
    for gy in range(n):
        for gx in range(n):
            x = gx * spacing - half
            y = gy * spacing - half
            if abs(x) < 14 and abs(y) < 14:
                continue
            h = 1.0 + 4.0 * (0.5 + 0.5 * math.sin(gx * 0.7) * math.cos(gy * 0.5))
            r = 0.45 + 0.4 * (gx / n)
            b = 0.45 + 0.4 * (gy / n)
            out += box(f"tower_{gx}_{gy}", (x, y, h / 2), (1.6, 1.6, h), (r, 0.55, b), collider=False)
    # Animated mannequins in a ring: their Animators live in a scene activated after the hub's.
    for i in range(12):
        a = i / 12 * math.tau
        yaw = math.degrees(a) + 90
        out += (f"    - name: dancer_{i}\n"
                "      prefab: objects/mannequin\n"
                "      components:\n"
                "        - type: Transform\n"
                f"          position: {v3(math.cos(a) * 9, math.sin(a) * 9, 0)}\n"
                f"          rotation: {v3(0, 0, yaw)}\n"
                "          scale: { x: 1, y: 1, z: 1 }\n")
    out += camera(11.0, 30.0)
    out += sun()
    write("heavy.yaml", out)


if __name__ == "__main__":
    os.makedirs(ROOT, exist_ok=True)
    hub()
    heavy()
