#!/usr/bin/env python3
"""Writes assets/scenes/tests/animation/skinning_stress/scene.yaml: a 10x5 grid of 50 skinned
tentacle prefabs (objects/animation/tentacle.yaml) -- the PROFILE scene for GPU vs CPU skinning
(render.skinning: gpu | cpu)."""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "scenes", "tests", "animation", "skinning_stress", "scene.yaml")

lines = [
    "# skinning_stress -- 50 skinned tentacles (the animation_test rig) for GPU-vs-CPU skinning",
    "# PROFILE runs (render.skinning: gpu | cpu).",
    "# GENERATED by tools/gen_skinning_stress_scene.py; edit that, not this file.",
    "format: blender",
    "scene:",
    "  scene_name: skinning_stress",
    "  root_objects:",
    "    - name: ground",
    "      components:",
    "        - type: Transform",
    "          position: {x: 0, y: 0, z: -0.05}",
    "          scale: {x: 24, y: 14, z: 0.1}",
    "        - type: MeshRenderer",
    "          mesh_path: cube",
    "          material: {albedo: {r: 0.42, g: 0.45, b: 0.48}, metallic: 0.0, roughness: 0.9}",
    "      children: []",
]
for i in range(50):
    x = -9.0 + (i % 10) * 2.0
    y = -4.0 + (i // 10) * 2.0
    lines += [
        f"    - name: tentacle_{i:02d}",
        "      prefab: objects/tentacle",
        "      components:",
        "        - type: Transform",
        f"          position: {{x: {x:.1f}, y: {y:.1f}, z: 0}}",
        f"          rotation: {{x: 0, y: 0, z: {(i * 37) % 360}}}",
    ]
lines += [
    "    - name: camera",
    "      components:",
    "        - type: Transform",
    "          position: {x: 0, y: -16, z: 7}",
    "          rotation: {x: 68, y: 0, z: 0}",
    "        - type: Camera",
    "          main: true",
    "          fov: 60.0",
    "      children: []",
    "    - name: sun",
    "      components:",
    "        - type: Transform",
    "        - type: DirectionalLight",
    "          direction: {x: -0.45, y: 0.4, z: -0.8}",
    "          color: {r: 1.0, g: 0.96, b: 0.9}",
    "          intensity: 1.3",
    "          cast_shadows: true",
    "      children: []",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT)
