#!/usr/bin/env python3
"""Writes the `mannequin`: a humanoid object-hierarchy rig, its capsule part meshes and its clips.

Outputs (all under assets/):
  * objects/characters/mannequin.yaml -- the rig as an OBJECT ASSET (prefab). Place it with
    `prefab: objects/mannequin`; add a CharacterController (+ CharacterAnimDriver) to the
    instance to make it a player (see scenes/gameplay/character_demo).
  * objects/characters/mannequin_ragdoll.yaml -- the same rig plus a Ragdoll (capsule/box bones,
    cone-twist hips/shoulders/spine/neck, hinge knees/elbows/ankles; see RAGDOLL below and
    toyengine/scene/ragdoll.h). A separate prefab, so plain mannequins carry no bone bodies.
  * objects/characters/mannequin_ik.yaml -- the same rig FULLY IK-driven: no clip touches a
    bone. Its clips (animations/mannequin_ik/) key only target empties -- foot / hand targets,
    knee / elbow poles, a chest target, a look target -- and IK poses every bone from them:
    TwoBoneIK legs and arms (match_target_rotation), a ChainIK spine, a LookAtIK head. The IK
    clips are BAKED from the keyframed ones (forward kinematics, every frame), so it moves like
    the plain mannequin; FootIK on it adjusts the foot targets (mode auto -> targets).
  * meshes/characters/mannequin_*.yaml -- one capsule mesh per body part (Z-up, centred).
  * animations/mannequin/{idle,walk,run,jump}.yaml -- the clips its Animator plays. walk and run
    carry ROOT MOTION (the pelvis's travel, `root_motion: {object: pelvis, translation: xy}`) and
    `footstep` events (string left / right) as each foot plants.
  * animations/mannequin_ik/{idle,walk,run,jump}.yaml -- the same motion as target tracks.

The rig, Z-up and facing local +Y (its right hand is +X, its left -X), origin at the feet,
about 1.8 m tall -- the default CharacterController capsule (radius 0.3, height 1.8):

  mannequin                      Animator (idle / walk / run / jump)
    pelvis                       z 0.95
      spine                        abdomen
        chest                      torso
          neck
            head                   head + visor (the visor marks the front)
          upper_arm_l / _r         shoulders at x -/+0.21
            lower_arm_l / _r
              hand_l / _r
      thigh_l / _r                 hips at x -/+0.1
        shin_l / _r
          foot_l / _r

Joints are empty objects at their pivots with identity rest rotations; limbs hang along local
-Z, so a positive X rotation swings a limb FORWARD (+Y) and a negative one bends a knee back.
Each visible part is a child `<joint>_shape` of its joint. These names are the rig's contract:
clips address joints by path, and later systems (foot IK, ragdoll bone lists) name them too.

Run:  python3 tools/gen_mannequin.py
"""

import math
import os

ASSETS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets")
MESH_DIR = os.path.join(ASSETS, "meshes", "characters")
OBJECT_PATH = os.path.join(ASSETS, "objects", "characters", "mannequin.yaml")
RAGDOLL_OBJECT_PATH = os.path.join(ASSETS, "objects", "characters", "mannequin_ragdoll.yaml")
IK_OBJECT_PATH = os.path.join(ASSETS, "objects", "characters", "mannequin_ik.yaml")
ANIM_DIR = os.path.join(ASSETS, "animations", "mannequin")
IK_ANIM_DIR = os.path.join(ASSETS, "animations", "mannequin_ik")

GENERATED = "GENERATED by tools/gen_mannequin.py; edit that, not this file."


def fmt(v):
    return "[" + ", ".join(f"{x:.6g}" for x in v) + "]"


def num(x):
    return f"{x:.6g}"


# ---------------------------------------------------------------------------------------------
# Capsule meshes
# ---------------------------------------------------------------------------------------------

def capsule_mesh(path, radius, length, sides=16, cap_rings=6):
    """A capsule along Z centred at the origin: `length` between the cap centres (0 = sphere).

    A lathe: rings from the bottom pole to the top pole, a duplicated u = 1 seam column, and
    triangles (not degenerate quads) at the poles.
    """
    half = length * 0.5
    rings = []  # (radius at ring, z, normal_r, normal_z, v)
    for i in range(cap_rings + 1):  # bottom cap, pole -> equator
        a = -math.pi / 2 + (math.pi / 2) * i / cap_rings
        rings.append((radius * math.cos(a), -half + radius * math.sin(a), math.cos(a), math.sin(a)))
    for i in range(cap_rings + 1):  # top cap, equator -> pole
        a = (math.pi / 2) * i / cap_rings
        rings.append((radius * math.cos(a), half + radius * math.sin(a), math.cos(a), math.sin(a)))
    total = (length + 2 * radius) or 1.0
    verts, normals, uvs, faces = [], [], [], []
    row = sides + 1
    for (rr, z, nr, nz) in rings:
        v = (z + half + radius) / total
        for s in range(sides + 1):
            a = 2 * math.pi * s / sides
            c, sn = math.cos(a), math.sin(a)
            verts.append([rr * c, rr * sn, z])
            n = [nr * c, nr * sn, nz]
            ln = math.sqrt(sum(x * x for x in n)) or 1.0
            normals.append([x / ln for x in n])
            uvs.append([s / sides, v])
    last = len(rings) - 1
    for r in range(last):
        for s in range(sides):
            a = r * row + s
            b, c, d = a + 1, a + row + 1, a + row
            if r == 0:
                faces.append([a, c, d])          # bottom pole: ring 0 is a point
            elif r == last - 1:
                faces.append([a, b, c])          # top pole: ring `last` is a point
            else:
                faces.append([a, b, c, d])
    lines = [f"# mannequin part: capsule r {num(radius)}, cap-centre distance {num(length)}, along Z, centred.",
             f"# {GENERATED}",
             "vertices:"]
    lines += [f"  - {fmt([round(x, 5) for x in p])}" for p in verts]
    lines.append("normals:")
    lines += [f"  - {fmt([round(x, 5) for x in n])}" for n in normals]
    lines.append("uvs:")
    lines += [f"  - {fmt([round(x, 5) for x in uv])}" for uv in uvs]
    lines.append("faces:")
    lines += [f"  - {f}" for f in faces]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


# name -> (radius, cap-centre length)
PART_MESHES = {
    "mannequin_pelvis": (0.13, 0.14),
    "mannequin_abdomen": (0.12, 0.08),
    "mannequin_torso": (0.16, 0.14),
    "mannequin_head": (0.11, 0.05),
    "mannequin_neck": (0.05, 0.04),
    "mannequin_upper_arm": (0.055, 0.17),
    "mannequin_lower_arm": (0.047, 0.16),
    "mannequin_hand": (0.045, 0.05),
    "mannequin_thigh": (0.08, 0.27),
    "mannequin_shin": (0.062, 0.29),
    "mannequin_foot": (0.05, 0.13),
}


# ---------------------------------------------------------------------------------------------
# The rig
# ---------------------------------------------------------------------------------------------

BODY = "{albedo: {r: 0.62, g: 0.66, b: 0.72}, roughness: 0.55, metallic: 0.05}"
LIMB = "{albedo: {r: 0.5, g: 0.54, b: 0.6}, roughness: 0.55, metallic: 0.05}"
DARK = "{albedo: {r: 0.2, g: 0.22, b: 0.26}, roughness: 0.6}"
VISOR = "{albedo: {r: 0.95, g: 0.55, b: 0.15}, roughness: 0.35, emissive: {r: 0.4, g: 0.18, b: 0.04}}"


def joint(name, pos, children, shapes=()):
    return {"name": name, "pos": pos, "children": list(shapes) + list(children)}


def shape(name, mesh, pos, material, rot=(0, 0, 0), scale=(1, 1, 1)):
    return {"name": name, "pos": pos, "rot": rot, "scale": scale, "mesh": mesh, "material": material}


def arm(side):
    sx = -1 if side == "l" else 1
    return joint(f"upper_arm_{side}", (sx * 0.21, 0, 0.17), [
        joint(f"lower_arm_{side}", (0, 0, -0.28), [
            joint(f"hand_{side}", (0, 0, -0.25), [], [
                shape(f"hand_{side}_shape", "mannequin_hand", (0, 0, -0.07), DARK)]),
        ], [shape(f"lower_arm_{side}_shape", "mannequin_lower_arm", (0, 0, -0.125), LIMB)]),
    ], [shape(f"upper_arm_{side}_shape", "mannequin_upper_arm", (0, 0, -0.14), LIMB)])


def leg(side):
    sx = -1 if side == "l" else 1
    return joint(f"thigh_{side}", (sx * 0.1, 0, -0.05), [
        joint(f"shin_{side}", (0, 0, -0.43), [
            joint(f"foot_{side}", (0, 0, -0.41), [], [
                shape(f"foot_{side}_shape", "mannequin_foot", (0, 0.06, -0.005), DARK, rot=(90, 0, 0))]),
        ], [shape(f"shin_{side}_shape", "mannequin_shin", (0, 0, -0.205), LIMB)]),
    ], [shape(f"thigh_{side}_shape", "mannequin_thigh", (0, 0, -0.215), LIMB)])


RIG = joint("pelvis", (0, 0, 0.95), [
    joint("spine", (0, 0, 0.1), [
        joint("chest", (0, 0, 0.2), [
            joint("neck", (0, 0, 0.24), [
                joint("head", (0, 0, 0.05), [], [
                    shape("head_shape", "mannequin_head", (0, 0, 0.11), BODY),
                    shape("visor", "cube", (0, 0.085, 0.13), VISOR, scale=(0.16, 0.06, 0.05)),
                ]),
            ], [shape("neck_shape", "mannequin_neck", (0, 0, 0.0), DARK)]),
            arm("l"), arm("r"),
        ], [shape("chest_shape", "mannequin_torso", (0, 0, 0.08), BODY, scale=(1.25, 0.8, 1.0))]),
    ], [shape("abdomen_shape", "mannequin_abdomen", (0, 0, 0.06), BODY, scale=(1.0, 0.8, 1.0))]),
    leg("l"), leg("r"),
], [shape("pelvis_shape", "mannequin_pelvis", (0, 0, 0.0), BODY, rot=(0, 90, 0), scale=(1.0, 0.8, 1.0))])


def vec(label, v):
    return f"{label}: {{x: {num(v[0])}, y: {num(v[1])}, z: {num(v[2])}}}"


def emit_node(node, indent):
    p = " " * indent
    out = [f"{p}- name: {node['name']}", f"{p}  components:", f"{p}    - type: Transform",
           f"{p}      {vec('position', node['pos'])}"]
    if "mesh" in node:
        out.append(f"{p}      {vec('rotation', node['rot'])}")
        out.append(f"{p}      {vec('scale', node['scale'])}")
        out.append(f"{p}    - type: MeshRenderer")
        out.append(f"{p}      mesh_path: {node['mesh']}")
        out.append(f"{p}      material: {node['material']}")
        out.append(f"{p}  children: []")
        return out
    out.append(f"{p}      rotation: {{x: 0, y: 0, z: 0}}")
    out.append(f"{p}  children:" + ("" if node["children"] else " []"))
    for child in node["children"]:
        out += emit_node(child, indent + 4)
    return out


# Ragdoll bones: (path, shape, shape params, mass kg, joint). Shapes sit along each bone toward
# its child (limbs hang along -Z); joints connect to the nearest ancestor bone in this list and
# are measured from the bind pose (identity rest rotations). Positive X swings a limb forward, so
# a knee bends in [-140, 0] and an elbow in [0, 140]. Hands and the neck stay out (they ride
# their parent bone): fewer, heavier bodies keep the chain stiff and calm.
def _vec(v):
    return "{x: %s, y: %s, z: %s}" % tuple(num(c) for c in v)


def _cone(axis, swing, twist, anchor=None):
    j = [("joint", "cone_twist")]
    if anchor:
        j.append(("anchor", _vec(anchor)))
    return j + [("axis", _vec(axis)), ("swing", num(swing)), ("twist_min", num(-twist)), ("twist_max", num(twist))]


def _hinge(lo, hi):
    return [("joint", "hinge"), ("axis", _vec((1, 0, 0))), ("limit_min", num(lo)), ("limit_max", num(hi))]


RAGDOLL = [
    ("pelvis", "capsule", {"radius": 0.12, "height": 0.32, "direction": "x"}, 12.0, None),
    ("pelvis/spine", "capsule", {"radius": 0.11, "height": 0.36, "direction": "x", "center": (0, 0, 0.08)}, 8.0,
     _cone((0, 0, 1), 25, 20)),
    ("pelvis/spine/chest", "capsule", {"radius": 0.13, "height": 0.44, "direction": "x", "center": (0, 0, 0.1)}, 12.0,
     _cone((0, 0, 1), 20, 20)),
    ("pelvis/spine/chest/neck/head", "sphere", {"radius": 0.12, "center": (0, 0, 0.11)}, 5.0,
     _cone((0, 0, 1), 35, 45, anchor=(0, 0, -0.05))),
]
for _s in "lr":
    RAGDOLL += [
        (f"pelvis/spine/chest/upper_arm_{_s}", "capsule", {"radius": 0.055, "height": 0.28, "center": (0, 0, -0.14)}, 2.5,
         _cone((0, 0, -1), 80, 45)),
        (f"pelvis/spine/chest/upper_arm_{_s}/lower_arm_{_s}", "capsule",
         {"radius": 0.04, "height": 0.36, "center": (0, 0, -0.17)}, 2.0, _hinge(0, 140)),
        (f"pelvis/thigh_{_s}", "capsule", {"radius": 0.08, "height": 0.43, "center": (0, 0, -0.215)}, 8.0,
         _cone((0, 0, -1), 60, 30)),
        (f"pelvis/thigh_{_s}/shin_{_s}", "capsule", {"radius": 0.062, "height": 0.41, "center": (0, 0, -0.205)}, 4.0,
         _hinge(-140, 0)),
        (f"pelvis/thigh_{_s}/shin_{_s}/foot_{_s}", "box", {"size": (0.1, 0.24, 0.08), "center": (0, 0.06, -0.015)}, 1.0,
         _hinge(-30, 40)),
    ]


def ragdoll_component():
    out = ["    - type: Ragdoll",
           "      mode: animated",
           "      blend_time: 0.6",
           "      recover_state: idle",
           "      drag: 0.05",
           "      angular_drag: 0.8",
           "      bones:"]
    for path, shape, params, mass, joint in RAGDOLL:
        out.append(f"        - bone: {path}")
        out.append(f"          shape: {shape}")
        for key in ("radius", "height", "direction"):
            if key in params:
                v = params[key]
                out.append(f"          {key}: {v if isinstance(v, str) else num(v)}")
        if "size" in params:
            out.append(f"          size: {_vec(params['size'])}")
        if "center" in params:
            out.append(f"          center: {_vec(params['center'])}")
        out.append(f"          mass: {num(mass)}")
        for key, value in joint or ():
            out.append(f"          {key}: {value}")
    return out


def write_object(path=OBJECT_PATH, extra_components=(), header_note=None, clip_dir="animations/mannequin",
                 extra_children=(), rig=None):
    lines = [
        "# mannequin: a 1.8 m humanoid object-hierarchy rig (joints are empties, parts are capsule",
        "# meshes), facing +Y, origin at the feet. Clips idle / walk / run / jump. Joint names are a",
        "# contract (clips, foot IK and ragdolls address them) -- see tools/gen_mannequin.py.",
    ]
    if header_note:
        lines.append(f"# {header_note}")
    lines += [
        f"# {GENERATED}",
        "object:",
        f"  name: {os.path.splitext(os.path.basename(path))[0]}",
        "  components:",
        "    - type: Transform",
        "      position: {x: 0, y: 0, z: 0}",
        "    - type: Animator",
        "      auto_play: idle",
        "      default_crossfade: 0.2",
        "      states:",
        f"        - {{name: idle, clip: {clip_dir}/idle.yaml}}",
        f"        - {{name: walk, clip: {clip_dir}/walk.yaml}}",
        f"        - {{name: run, clip: {clip_dir}/run.yaml}}",
        f"        - {{name: jump, clip: {clip_dir}/jump.yaml, wrap: once}}",
    ]
    lines += list(extra_components)
    lines.append("  children:")
    lines += emit_node(rig or RIG, 4)
    lines += list(extra_children)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------------------------
# Clips
# ---------------------------------------------------------------------------------------------

PATHS = {
    "pelvis": "pelvis",
    "spine": "pelvis/spine",
    "chest": "pelvis/spine/chest",
    "head": "pelvis/spine/chest/neck/head",
}
for _s in "lr":
    PATHS[f"upper_arm_{_s}"] = f"pelvis/spine/chest/upper_arm_{_s}"
    PATHS[f"lower_arm_{_s}"] = f"pelvis/spine/chest/upper_arm_{_s}/lower_arm_{_s}"
    PATHS[f"thigh_{_s}"] = f"pelvis/thigh_{_s}"
    PATHS[f"shin_{_s}"] = f"pelvis/thigh_{_s}/shin_{_s}"
    PATHS[f"foot_{_s}"] = f"pelvis/thigh_{_s}/shin_{_s}/foot_{_s}"


def qmul(a, b):
    ax, ay, az, aw = a
    bx, by, bz, bw = b
    return [aw * bx + ax * bw + ay * bz - az * by,
            aw * by - ax * bz + ay * bw + az * bx,
            aw * bz + ax * by - ay * bx + az * bw,
            aw * bw - ax * bx - ay * by - az * bz]


def quat_xyz(x_deg, y_deg=0.0, z_deg=0.0):
    """Rotation X first, then Y, then Z (matches the Transform's Euler order)."""
    def axis(i, deg):
        a = math.radians(deg) * 0.5
        q = [0.0, 0.0, 0.0, math.cos(a)]
        q[i] = math.sin(a)
        return q
    return qmul(axis(2, z_deg), qmul(axis(1, y_deg), axis(0, x_deg)))


def rot_track(joint_name, samples, easing="linear"):
    """samples: [(time, (x_deg, y_deg, z_deg))]; keeps keys in one quaternion hemisphere."""
    keys, prev = [], None
    for t, angles in samples:
        q = quat_xyz(*angles)
        if prev is not None and sum(a * b for a, b in zip(q, prev)) < 0:
            q = [-c for c in q]
        prev = q
        keys.append((t, [round(c, 6) for c in q]))
    return (PATHS[joint_name], "rotation_quat", keys, easing)


def pos_track(joint_name, channel, samples, easing="linear"):
    return (PATHS[joint_name], f"position.{channel}", [(t, v) for t, v in samples], easing)


FPS = 30  # the editor Timeline's frame grid (editor/app/ui/timeline.inl, kAnimFps): keys land on it


def on_frame(t):
    """`t` snapped to the nearest frame of the Timeline's grid, so every key sits on a tick."""
    return round(t * FPS) / FPS


CLIPS = {}  # name -> the keyframed clip's data, for bake_ik_clip()


def write_clip(name, length, tracks, wrap="loop", events=(), root_motion=None, anim_dir=ANIM_DIR, label="mannequin"):
    """events: [(time, name, string)]; root_motion: (object, translation, rotation) or None.
    Key and event times are snapped to whole frames (on_frame); `length` must already be one.
    Key values are numbers (one channel) or lists (a vector / quaternion)."""
    if anim_dir == ANIM_DIR:
        CLIPS[name] = {"length": length, "tracks": tracks, "wrap": wrap, "events": events, "root_motion": root_motion}
    assert abs(length * FPS - round(length * FPS)) < 1e-6, f"{name}: length {length} is not a whole frame"
    lines = [f"# {label} {name}. {GENERATED}", "clip:", f"  name: {name}", f"  wrap: {wrap}",
             f"  length: {num(length)}"]
    if root_motion:
        obj, translation, rotation = root_motion
        lines.append(f"  root_motion: {{object: {obj}, translation: {translation}, rotation: {rotation}}}")
    if events:
        lines.append("  events:")
        for t, ev_name, ev_str in events:
            lines.append(f"    - {{time: {num(round(on_frame(t), 4))}, name: {ev_name}, string: {ev_str}}}")
    lines.append("  tracks:")
    for path, prop, keys, easing in tracks:
        lines.append(f"    - object: {path}")
        lines.append(f"      property: {prop}")
        lines.append("      keys:")
        frames = [round(t * FPS) for t, _ in keys]
        assert len(set(frames)) == len(frames), f"{name}: two {path} keys snap to one frame"
        for t, v in keys:
            ease = "" if easing == "linear" else f", easing: {easing}"
            val = fmt(v) if isinstance(v, (list, tuple)) else num(v)
            lines.append(f"        - {{time: {num(round(on_frame(t), 4))}, value: {val}{ease}}}")
    os.makedirs(anim_dir, exist_ok=True)
    with open(os.path.join(anim_dir, f"{name}.yaml"), "w") as fh:
        fh.write("\n".join(lines) + "\n")


def cycle(length, n, fn):
    """n + 1 samples of fn(phase in [0, 1]) over one loop, the last equal to the first."""
    return [(length * i / n, fn((i % n) / n)) for i in range(n + 1)]


def gait(name, length, stride, knee, arm_swing, elbow, lean, bob, pelvis_z, travel, n=12):
    """A walk/run cycle: legs in antiphase, arms against the legs, knees bent during swing.

    The pelvis travels `travel` metres along +Y per cycle -- the clip's ROOT MOTION (pelvis, xy):
    the Animator holds the pelvis in place and hands the travel to its owner (a CharacterController
    with use_root_motion moves by it; anything else just plays the gait in place). A footstep
    event fires as each foot plants: the left thigh is furthest forward at phase 0.25, the right
    at 0.75.
    """
    tau = 2 * math.pi

    def thigh(phase, side):
        return stride * math.sin(tau * phase + (0 if side == "l" else math.pi))

    def shin(phase, side):
        p = tau * phase + (0 if side == "l" else math.pi)
        return -(5 + knee * max(0.0, math.cos(p)) ** 1.5)

    tracks = [pos_track("pelvis", "z", cycle(length, n, lambda p: pelvis_z - bob * math.cos(2 * tau * p))),
              pos_track("pelvis", "y", [(0.0, 0.0), (length, travel)])]
    tracks.append(rot_track("spine", cycle(length, n, lambda p: (-lean, 0, 0))))
    tracks.append(rot_track("chest", cycle(length, n, lambda p: (0, 0, 4 * math.sin(tau * p)))))
    tracks.append(rot_track("head", cycle(length, n, lambda p: (lean * 0.6, 0, -4 * math.sin(tau * p)))))
    for side in "lr":
        abduct = 7 if side == "l" else -7
        tracks.append(rot_track(f"thigh_{side}", cycle(length, n, lambda p, s=side: (thigh(p, s), 0, 0))))
        tracks.append(rot_track(f"shin_{side}", cycle(length, n, lambda p, s=side: (shin(p, s), 0, 0))))
        tracks.append(rot_track(f"foot_{side}", cycle(length, n,
                                                      lambda p, s=side: (-0.5 * (thigh(p, s) + shin(p, s)), 0, 0))))
        tracks.append(rot_track(f"upper_arm_{side}", cycle(length, n,
                                                           lambda p, s=side: (-arm_swing / stride * thigh(p, s), abduct, 0))))
        tracks.append(rot_track(f"lower_arm_{side}", cycle(length, n,
                                                           lambda p, s=side: (elbow + 0.3 * arm_swing / stride * max(0.0, -thigh(p, s)), 0, 0))))
    events = [(0.25 * length, "footstep", "left"), (0.75 * length, "footstep", "right")]
    write_clip(name, length, tracks, events=events, root_motion=("pelvis", "xy", "none"))


def idle():
    length, n, tau = 2.4, 8, 2 * math.pi
    breathe = lambda p: math.sin(tau * p)
    tracks = [
        pos_track("pelvis", "z", cycle(length, n, lambda p: 0.95 - 0.006 * (1 - breathe(p)))),
        rot_track("chest", cycle(length, n, lambda p: (-1.5 * breathe(p), 0, 0)), "ease_in_out"),
        rot_track("head", cycle(length, n, lambda p: (1.0 * breathe(p), 0, 3 * math.sin(tau * p * 0.5 * 2))), "ease_in_out"),
    ]
    for side in "lr":
        sgn = 1 if side == "l" else -1
        tracks.append(rot_track(f"upper_arm_{side}", cycle(length, n, lambda p, g=sgn: (2 * breathe(p), g * (7 + 1.5 * breathe(p)), 0)), "ease_in_out"))
        tracks.append(rot_track(f"lower_arm_{side}", cycle(length, n, lambda p: (12 + 2 * breathe(p), 0, 0)), "ease_in_out"))
        tracks.append(rot_track(f"thigh_{side}", cycle(length, n, lambda p: (2, 0, 0))))
        tracks.append(rot_track(f"shin_{side}", cycle(length, n, lambda p: (-4, 0, 0))))
        tracks.append(rot_track(f"foot_{side}", cycle(length, n, lambda p: (2, 0, 0))))
    write_clip("idle", length, tracks)


def jump():
    # Once: a quick tuck into the air pose, held. Played while airborne.
    key = lambda pose: [(0.0, pose[0]), (0.18, pose[1]), (0.5, pose[1])]
    tracks = [
        pos_track("pelvis", "z", [(0.0, 0.95), (0.18, 0.95), (0.5, 0.95)], "ease_out"),
        rot_track("spine", key([(0, 0, 0), (-8, 0, 0)]), "ease_out"),
        rot_track("head", key([(0, 0, 0), (6, 0, 0)]), "ease_out"),
    ]
    for side in "lr":
        sgn = 1 if side == "l" else -1
        lead = side == "l"
        tracks.append(rot_track(f"thigh_{side}", key([(2, 0, 0), (55 if lead else 15, 0, 0)]), "ease_out"))
        tracks.append(rot_track(f"shin_{side}", key([(-4, 0, 0), (-75 if lead else -40, 0, 0)]), "ease_out"))
        tracks.append(rot_track(f"foot_{side}", key([(2, 0, 0), (15, 0, 0)]), "ease_out"))
        tracks.append(rot_track(f"upper_arm_{side}", key([(0, sgn * 7, 0), (35 if lead else -25, sgn * 35, 0)]), "ease_out"))
        tracks.append(rot_track(f"lower_arm_{side}", key([(12, 0, 0), (45, 0, 0)]), "ease_out"))
    write_clip("jump", 0.5, tracks, wrap="once")



# ---------------------------------------------------------------------------------------------
# The fully IK mannequin: forward kinematics of the keyframed clips, baked into target tracks
# ---------------------------------------------------------------------------------------------

def _joints(node, parent=None, out=None):
    """name -> (rest position, parent name) for every joint (shapes skipped)."""
    out = {} if out is None else out
    if "mesh" in node:
        return out
    out[node["name"]] = (tuple(node["pos"]), parent)
    for c in node["children"]:
        _joints(c, node["name"], out)
    return out


JOINTS = _joints(RIG)


def qrot(q, v):
    """Rotates vector v by unit quaternion q (x, y, z, w)."""
    return qmul(qmul(q, [v[0], v[1], v[2], 0.0]), [-q[0], -q[1], -q[2], q[3]])[:3]


def ease(mode, t):
    """coopa::anim::apply_easing."""
    if mode == "step":
        return 0.0
    if mode == "ease_in":
        return t * t
    if mode == "ease_out":
        return t * (2.0 - t)
    if mode == "ease_in_out":
        return 2.0 * t * t if t < 0.5 else 1.0 - 2.0 * (1.0 - t) * (1.0 - t)
    return t


def sample_track(keys, easing, t):
    """The track's value at t as the Animator samples it: clamped ends, the left key's easing,
    lists blended per component (a quaternion is then normalised: nlerp)."""
    times = [on_frame(k) for k, _ in keys]
    vals = [v for _, v in keys]
    if t <= times[0]:
        return vals[0]
    if t >= times[-1]:
        return vals[-1]
    i = max(j for j in range(len(times)) if times[j] <= t)
    span = times[i + 1] - times[i]
    u = ease(easing, (t - times[i]) / span if span > 0 else 0.0)
    a, b = vals[i], vals[i + 1]
    if isinstance(a, list):
        return [x + (y - x) * u for x, y in zip(a, b)]
    return a + (b - a) * u


def fk_pose(clip, t):
    """World (= mannequin-root) position and rotation of every joint at time t. Root motion's
    translation is held at the clip's start, as the Animator holds it."""
    local_pos = {n: list(p) for n, (p, _) in JOINTS.items()}
    local_rot = {n: [0.0, 0.0, 0.0, 1.0] for n in JOINTS}
    held = set(clip["root_motion"][1]) if clip["root_motion"] else set()
    for path, prop, keys, easing in clip["tracks"]:
        name = path.split("/")[-1]
        if prop == "rotation_quat":
            q = sample_track(keys, easing, t)
            ln = math.sqrt(sum(c * c for c in q)) or 1.0
            local_rot[name] = [c / ln for c in q]
        elif prop.startswith("position."):
            ch = prop.split(".")[1]
            local_pos[name]["xyz".index(ch)] = keys[0][1] if ch in held else sample_track(keys, easing, t)
    world = {}

    def walk(name):
        if name in world:
            return world[name]
        parent = JOINTS[name][1]
        if parent is None:
            world[name] = (local_pos[name], local_rot[name])
        else:
            pp, pr = walk(parent)
            off = qrot(pr, local_pos[name])
            world[name] = ([pp[i] + off[i] for i in range(3)], qmul(pr, local_rot[name]))
        return world[name]

    for n in JOINTS:
        walk(n)
    return world


def _pole(top, mid, end, fallback, dist=0.5):
    """A point the middle joint (knee / elbow) bends toward: off the top-end line, through mid."""
    axis = [end[i] - top[i] for i in range(3)]
    al = math.sqrt(sum(c * c for c in axis)) or 1.0
    axis = [c / al for c in axis]
    rel = [mid[i] - top[i] for i in range(3)]
    d = sum(rel[i] * axis[i] for i in range(3))
    perp = [rel[i] - axis[i] * d for i in range(3)]
    pl = math.sqrt(sum(c * c for c in perp))
    dirv = [c / pl for c in perp] if pl > 0.01 else list(fallback)
    return [mid[i] + dirv[i] * dist for i in range(3)]


LOOK_DISTANCE = 2.0


def ik_targets(world):
    """object name -> (position, rotation or None) for every IK target of the mannequin_ik."""
    out = {}
    for s in "lr":
        out[f"foot_target_{s}"] = (world[f"foot_{s}"][0], world[f"foot_{s}"][1])
        out[f"knee_pole_{s}"] = (_pole(world[f"thigh_{s}"][0], world[f"shin_{s}"][0], world[f"foot_{s}"][0], (0, 1, 0)), None)
        out[f"hand_target_{s}"] = (world[f"hand_{s}"][0], world[f"hand_{s}"][1])
        out[f"elbow_pole_{s}"] = (_pole(world[f"upper_arm_{s}"][0], world[f"lower_arm_{s}"][0], world[f"hand_{s}"][0],
                                        (0, -1, 0)), None)
    out["spine_target"] = (world["chest"][0], world["chest"][1])
    hp, hr = world["head"]
    fwd = qrot(hr, (0, 1, 0))
    out["look_target"] = ([hp[i] + fwd[i] * LOOK_DISTANCE for i in range(3)], None)
    return out


IK_TARGET_NAMES = [f"{k}_{s}" for k in ("foot_target", "knee_pole", "hand_target", "elbow_pole") for s in "lr"] + \
                  ["spine_target", "look_target"]
# Where each target hangs: the feet and knees from the mannequin root -- ground-relative, so a
# planted foot stays put however the body moves -- and the upper body's from the pelvis, as the
# bones they stand for do: a pelvis lowered by FootIK carries the hands, chest and gaze with it.
UPPER_BODY_TARGETS = {f"{k}_{s}" for k in ("hand_target", "elbow_pole") for s in "lr"} | {"spine_target", "look_target"}


def target_path(obj):
    return f"{PATHS['pelvis']}/{obj}" if obj in UPPER_BODY_TARGETS else obj


def bake_ik_clip(name):
    """Writes animations/mannequin_ik/<name>.yaml: the keyframed clip's pelvis tracks (and its
    root motion and events) as they are, and every IK target keyed on every frame from the clip's
    forward kinematics -- so the IK rig reproduces the keyframed motion."""
    clip = CLIPS[name]
    frames = round(clip["length"] * FPS)
    poses = [fk_pose(clip, i / FPS) for i in range(frames + 1)]
    samples = [ik_targets(w) for w in poses]
    tracks = [tr for tr in clip["tracks"] if tr[0] == PATHS["pelvis"]]
    for obj in IK_TARGET_NAMES:
        def local(i):
            p = samples[i][obj][0]
            if obj not in UPPER_BODY_TARGETS:
                return p
            pelvis_p, pelvis_r = poses[i]["pelvis"]
            assert abs(pelvis_r[3]) > 0.999999, "the pelvis never rotates in these clips"
            return [p[k] - pelvis_p[k] for k in range(3)]
        pos_keys = [(i / FPS, [round(c, 5) for c in local(i)]) for i in range(frames + 1)]
        tracks.append((target_path(obj), "position", pos_keys, "linear"))
        if samples[0][obj][1] is not None:
            rot_keys, prev = [], None
            for i in range(frames + 1):
                q = samples[i][obj][1]
                if prev is not None and sum(a * b for a, b in zip(q, prev)) < 0:
                    q = [-c for c in q]
                prev = q
                rot_keys.append((i / FPS, [round(c, 6) for c in q]))
            tracks.append((target_path(obj), "rotation_quat", rot_keys, "linear"))
    write_clip(name, clip["length"], tracks, wrap=clip["wrap"], events=clip["events"], root_motion=clip["root_motion"],
               anim_dir=IK_ANIM_DIR, label="mannequin_ik")


def ik_components():
    """The mannequin_ik's solvers: a spine chain, two-bone arms and legs, a look-at head."""
    out = ["    # Spine first (a chain: spine > chest; the chest takes its target's rotation, twist and",
           "    # all, and the neck rides on it), then the limbs hanging from it, then the head --",
           "    # IkSystem's default order for equal priorities.",
           "    - type: ChainIK",
           f"      root: {PATHS['spine']}",
           f"      tip: {PATHS['chest']}",
           "      target: spine_target",
           "      match_target_rotation: true"]
    for s in "lr":
        out += ["    - type: TwoBoneIK",
                f"      upper: {PATHS[f'thigh_{s}']}",
                f"      lower: {PATHS[f'shin_{s}']}",
                f"      end: {PATHS[f'foot_{s}']}",
                f"      target: foot_target_{s}",
                f"      pole: knee_pole_{s}",
                "      soft_limit: 0.0",
                "      match_target_rotation: true",
                "    - type: TwoBoneIK",
                f"      upper: {PATHS[f'upper_arm_{s}']}",
                f"      lower: {PATHS[f'lower_arm_{s}']}",
                f"      end: {PATHS[f'lower_arm_{s}']}/hand_{s}",
                f"      target: hand_target_{s}",
                f"      pole: elbow_pole_{s}",
                "      soft_limit: 0.0",
                "      match_target_rotation: true"]
    out += ["    - type: LookAtIK",
            f"      bone: {PATHS['head']}",
            "      target: look_target",
            "      max_angle: 89"]
    return out


def ik_rig():
    """RIG with the upper-body target empties added under the pelvis, at their rest places."""
    rest_world = fk_pose({"tracks": [], "root_motion": None}, 0.0)
    rest = ik_targets(rest_world)
    pelvis_p = rest_world["pelvis"][0]
    extra = [joint(obj, tuple(round(rest[obj][0][k] - pelvis_p[k], 5) for k in range(3)), [])
             for obj in IK_TARGET_NAMES if obj in UPPER_BODY_TARGETS]
    return dict(RIG, children=RIG["children"] + extra)


def ik_target_children():
    """The feet's and knees' target empties: children of the mannequin root, at their rest places."""
    rest = ik_targets(fk_pose({"tracks": [], "root_motion": None}, 0.0))
    out = []
    for obj in IK_TARGET_NAMES:
        if obj in UPPER_BODY_TARGETS:
            continue
        p = rest[obj][0]
        out += [f"    - name: {obj}",
                "      components:",
                "        - type: Transform",
                f"          {vec('position', [round(c, 5) for c in p])}",
                "          rotation: {x: 0, y: 0, z: 0}",
                "      children: []"]
    return out


def main():
    os.makedirs(MESH_DIR, exist_ok=True)
    for name, (r, length) in PART_MESHES.items():
        capsule_mesh(os.path.join(MESH_DIR, f"{name}.yaml"), r, length)
    write_object()
    write_object(RAGDOLL_OBJECT_PATH, ragdoll_component(),
                 "With a Ragdoll: R (input_toggle) or Ragdoll::activate() goes limp, deactivate() recovers.")
    idle()
    # Travel per cycle ~ two foot strides (2 x 2 x leg 0.84 x sin(stride)): walk ~1.6 m/s, run ~5.3 m/s.
    gait("walk", 0.9, stride=26, knee=55, arm_swing=22, elbow=15, lean=3, bob=0.02, pelvis_z=0.94, travel=1.45)
    gait("run", 0.6, stride=44, knee=95, arm_swing=45, elbow=70, lean=12, bob=0.04, pelvis_z=0.9, travel=3.2)
    jump()
    for clip in ("idle", "walk", "run", "jump"):
        bake_ik_clip(clip)
    write_object(IK_OBJECT_PATH, ik_components(),
                 "Fully IK: its clips key only the *_target / *_pole empties; IK poses every bone (see the generator).",
                 clip_dir="animations/mannequin_ik", extra_children=ik_target_children(), rig=ik_rig())
    print("wrote", OBJECT_PATH, "+", RAGDOLL_OBJECT_PATH, "+", IK_OBJECT_PATH, "+", len(PART_MESHES),
          "meshes + 4 clips + 4 IK clips")


if __name__ == "__main__":
    main()
